"""
Extra caption patterns per subcategory for the Megalith gap filler.

Catalogue subcategory names ("adult woman portrait", "ocean coast") rarely
appear verbatim in natural captions, so each subcategory can also match these
case-insensitive regex fragments. The filler only looks at the start of the
caption (MEGALITH_MATCH_MAX_CHARS), where the main subject is named.
"""

_P = r"(?:smil\w*|pos\w*|looks? (?:at|into) the camera|stares?|gaz\w+|portrait|headshot|close-up)"


def _portrait(who: str) -> list[str]:
    return [rf"portrait of (?:a|an|two|the)? ?(?:\w+ )?{who}",
            rf"{who}\b[^.;]{{0,45}}\b{_P}",
            rf"close-up of (?:a|an) (?:\w+ )?{who}"]


ALIASES: dict[str, list[str]] = {
    # Abstract & Textures
    "reflections": [r"reflect(?:ed|ion|ions|ing|s)\b", r"mirror(?:ed|s)?\b", r"mirror image"],
    "marble texture": [r"marble (?:surface|slab|floor|wall|counter\w*|column|pattern)"],
    "wood grain": [r"wooden (?:surface|plank|board|floor|texture|wall)", r"wood (?:texture|planks?|surface)"],
    "metal texture": [r"(?:metal|metallic|corrugated|steel) (?:surface|sheet|panel|texture|wall)"],
    "fabric texture": [r"(?:fabric|textile|cloth|knitted) (?:texture|pattern|surface|close-up)", r"close-up of (?:a )?(?:fabric|textile|cloth)"],
    "paper texture": [r"(?:crumpled|old|aged|handmade) paper", r"paper (?:texture|surface)"],
    "water ripples": [r"ripples?", r"rippling water", r"water surface"],
    "paint splash": [r"(?:paint|colou?rful) (?:splatter|splash|drip)\w*", r"splatter(?:ed)? paint"],
    "bokeh lights": [r"bokeh", r"blurr(?:ed|y) (?:lights|background of lights)", r"out-of-focus lights"],
    "color gradient": [r"gradient"],
    "concrete texture": [r"concrete (?:wall|surface|floor|texture|slab)", r"cracked concrete"],
    "rust and corrosion texture": [r"rust(?:y|ed|ing)?", r"corroded", r"corrosion"],
    "ice and frost texture": [r"frost(?:y|ed)?\b", r"ice crystals?", r"icicles?", r"frozen (?:surface|water|lake|puddle)"],
    "sand texture": [r"sand (?:ripples?|patterns?|texture|surface)", r"close-up of sand", r"footprints in the sand"],
    "liquid marbling": [r"marbl(?:ed|ing) (?:pattern|paint|paper)", r"swirl(?:s|ing)? of (?:colou?r|paint|liquid)"],
    # Agriculture & Farming
    "wheat field": [r"wheat", r"(?:golden|barley|grain) fields?", r"field of (?:wheat|barley|grain)"],
    "rice paddy": [r"rice (?:field|terrace)s?", r"paddy fields?", r"paddies"],
    "orchard": [r"(?:apple|cherry|fruit|olive|orange) (?:trees|grove)", r"grove"],
    "dairy farm": [r"dairy", r"(?:herd of )?(?:dairy )?cows? (?:graze|grazing|in a (?:barn|field|pasture))", r"milking"],
    "cattle ranch": [r"cattle", r"ranch\w*", r"cowboy", r"herd of cows"],
    "tractor in field": [r"tractors?", r"combine harvester"],
    "harvest scene": [r"harvest\w*", r"hay ?bales?", r"bales of hay"],
    "beekeeping apiary": [r"beekeep\w*", r"bee ?hives?", r"honeycomb", r"apiar\w*"],
    "poultry farm": [r"chickens? (?:in|on) a (?:farm|coop|barn)", r"chicken coop", r"hens?", r"poultry"],
    "irrigation system": [r"irrigat\w*", r"sprinklers?", r"water canal"],
    "farmers market stall": [r"farmers'? market", r"(?:produce|vegetable|fruit) (?:stand|stall|market)"],
    "vegetable field rows": [r"rows of (?:crops|vegetables|plants|lettuce|cabbage)", r"crop rows", r"(?:vegetable|crop|corn|cabbage|lettuce) fields?", r"cornfield"],
    # Animals & Wildlife
    "cheetah": [r"cheetahs?"],
    "rhinoceros": [r"rhinos?"],
    "hippopotamus": [r"hippos?", r"hippopotam\w+"],
    "gorilla": [r"gorillas?", r"silverback"],
    "chimpanzee": [r"chimps?", r"chimpanzees?", r"orangutans?", r"monkeys?", r"apes?"],
    "kangaroo": [r"kangaroos?", r"wallab\w+"],
    "koala": [r"koalas?"],
    "wild boar": [r"boars?", r"warthogs?", r"wild pigs?", r"feral (?:pig|hog)s?"],
    "hyena": [r"hyenas?", r"jackals?", r"wild dogs?"],
    "meerkat": [r"meerkats?", r"prairie dogs?", r"marmots?", r"groundhogs?", r"squirrels?", r"chipmunks?"],
    # Architecture & Buildings
    "glass office building": [r"glass (?:facade|building|tower|skyscraper)", r"office (?:building|tower|block)s?"],
    "apartment building": [r"apartment (?:block|complex|tower)s?", r"residential (?:building|tower|block)s?", r"high-rise"],
    "suburban house": [r"suburban", r"(?:two-story|single-family|brick|white|red|yellow|blue) houses?", r"houses? with a (?:front )?(?:yard|porch|lawn|garage)"],
    "luxury villa": [r"villas?", r"mansions?", r"estate house", r"manor"],
    "historic castle": [r"castles?", r"fortress\w*", r"fort\b", r"citadel", r"ramparts?", r"medieval (?:tower|wall)s?"],
    "industrial warehouse": [r"warehouses?", r"industrial (?:building|site|area)s?"],
    "wood cabin": [r"(?:log|wooden|rustic|mountain|small) cabins?", r"cabins?", r"cottages?", r"huts?"],
    "futuristic building": [r"futuristic", r"modern (?:architecture|building|structure)s?", r"(?:curved|geometric|contemporary) (?:building|architecture|structure)"],
    "bridge structure": [r"bridges?", r"viaducts?", r"aqueducts?", r"overpass"],
    "opera house": [r"opera house", r"theat(?:er|re) (?:building|facade|exterior)", r"concert hall"],
    "government building": [r"capitol", r"city hall", r"parliament", r"town hall", r"courthouse", r"(?:government|federal|state) (?:building|office)"],
    "school building": [r"school(?:house)?\b", r"(?:university|college) (?:building|campus)", r"campus"],
    "farmhouse": [r"farm ?houses?", r"barns?", r"farmsteads?", r"farm buildings?"],
    "skyscraper cluster skyline": [r"skyscrapers", r"(?:city|urban) skyline", r"skyline", r"high-rise buildings"],
    # Art & Design
    "wood carving": [r"(?:wood|wooden|stone) carvings?", r"carv(?:ed|ing|ings|er|ers)\b", r"totem poles?", r"(?:reliefs?|bas-relief)\b", r"(?:carved|sculpted) (?:wooden|wood|stone|figure|panel|door)"],
    "oil painting": [r"paintings?\b", r"painted (?:portrait|canvas|landscape)", r"canvas"],
    "pencil drawing": [r"(?:pencil|ink) (?:drawing|sketch)\w*", r"sketch\w*", r"drawings?"],
    "charcoal drawing": [r"charcoal", r"chalk (?:drawing|art)"],
    "ceramic art": [r"ceramics?", r"pottery", r"porcelain", r"(?:clay|ceramic) (?:vase|pot|bowl|sculpture)s?", r"vases?"],
    "street art": [r"murals?", r"graffiti"],
    "graphic design": [r"posters?", r"signage", r"(?:colou?rful|neon) signs?", r"logo"],
    "typography": [r"(?:large|bold|neon|painted|metal) (?:letters|lettering|text)", r"lettering", r"(?:word|letters) [\"']", r"signs? (?:reading|that reads)"],
    "3D render": [r"sculptures?", r"statues?", r"installation"],
    "stained glass art": [r"stained[- ]glass"],
    "mosaic art": [r"mosaics?", r"tiled (?:wall|floor|pattern)", r"tile work"],
    "printmaking": [r"printing press", r"prints?\b", r"engraving", r"etching", r"woodcut", r"letterpress"],
    "textile art": [r"quilts?", r"tapestr\w+", r"embroider\w*", r"textiles?"],
    "installation art": [r"(?:art|light) installation", r"art exhibit\w*", r"gallery", r"exhibition", r"museum (?:display|exhibit)"],
    "calligraphy art": [r"calligraph\w*", r"handwrit\w+", r"inscription"],
    # Beauty & Grooming
    "skincare": [r"(?:skin ?care|lotion|cream|moisturi\w+|serum)"],
    "hairstyling": [r"hair ?(?:styl\w+|dresser|salon|cut)", r"braid\w*", r"(?:styling|brushing|combing) (?:her|his) hair"],
    "barber haircut": [r"barber\w*", r"haircut", r"getting (?:a|his) hair cut"],
    "manicure": [r"manicur(?:e|es|ist|ists|ing)\b", r"nails? (?:salon|polish|art)", r"painted nails"],
    "perfume": [r"perfume", r"fragrance", r"cologne"],
    "hairbrush": [r"hair ?brush", r"combs?\b"],
    "electric razor": [r"razor", r"shav\w+"],
    "spa treatment": [r"\bspa\b", r"massag\w+", r"sauna", r"hot spring"],
    "facial care": [r"facial", r"(?:washing|cleansing) (?:her|his) face"],
    "eyeshadow palette": [r"eyeshadow", r"eye ?liner", r"make-?up (?:palette|brush|artist|kit)", r"cosmetics"],
    "hair coloring": [r"(?:dyed|bleached|colou?red|pink|blue|purple|green|red) hair", r"hair dye"],
    "beard grooming": [r"beard\w*", r"mustache", r"moustache"],
    "nail polish set": [r"nail polish", r"nail varnish"],
    "face mask treatment": [r"(?:clay|sheet|facial|beauty|mud|cucumber) masks?", r"(?:applying|applies) (?:a )?mask"],
    "eyebrow shaping": [r"eyebrows?", r"eyelash\w*", r"makeup applica\w+", r"applying (?:makeup|mascara|lipstick)"],
    # Birds
    "falcon": [r"falcons?", r"hawks?", r"kestrels?", r"buzzards?", r"harriers?", r"osprey"],
    "parrot": [r"parrots?", r"macaws?", r"cockatoos?", r"lorikeets?", r"parakeets?"],
    "woodpecker": [r"woodpeckers?", r"flickers?", r"nuthatch\w*"],
    "robin": [r"robins?", r"thrush\w*", r"bluebirds?", r"warblers?"],
    "sparrow": [r"sparrows?", r"finch\w*", r"small (?:brown )?birds?", r"songbirds?", r"wren\w*", r"chickadees?"],
    "toucan": [r"toucans?", r"hornbills?"],
    "crane bird": [r"cranes? (?:stand|wad|fly|flying|in (?:a|the) (?:field|marsh|wetland))", r"sandhill cranes?", r"storks?", r"egrets?", r"ibis\w*"],
    "vulture": [r"vultures?", r"condors?", r"buzzards?"],
    "kingfisher": [r"kingfishers?", r"bee-eaters?"],
    "cardinal bird": [r"cardinals?", r"red birds?", r"blue ?jays?", r"jays?\b", r"orioles?", r"tanagers?"],
    "ostrich": [r"ostrich\w*", r"emus?\b", r"rheas?\b"],
    # Business & Work
    "office meeting": [r"meeting", r"(?:group|people) (?:gathered |seated )?(?:around|at) a (?:conference |long )?table", r"panel discussion", r"business ?(?:men|women|people)"],
    "remote work": [r"(?:working|works) on (?:a|his|her) laptop", r"(?:uses|using|typing on) a laptop", r"laptop"],
    "software developer": [r"(?:programm|cod)(?:er|ing)", r"computer screens?", r"(?:works?|working) (?:at|on) (?:a|his|her) computer"],
    "designer workspace": [r"(?:cluttered |creative )?(?:desk|workspace|workbench|studio desk)", r"drawing table"],
    "retail worker": [r"cashier", r"(?:shop|store) (?:clerk|keeper|owner|assistant|worker)", r"(?:behind|at) (?:a|the) (?:counter|register)", r"vendor"],
    "warehouse worker": [r"forklift", r"warehouse", r"(?:boxes|pallets|crates) (?:stacked|in a)"],
    "chef at work": [r"(?:chef|cook)s? (?:in|prepar|cook|work|plat)\w*", r"kitchen staff", r"commercial kitchen"],
    "photographer at work": [r"photographers?", r"(?:holding|with|uses|using) a camera", r"takes? (?:a )?(?:photo|picture)s?"],
    "mechanic at work": [r"mechanics?", r"(?:repair|fix)\w* (?:a|the) (?:car|engine|vehicle|bike|motorcycle)", r"(?:auto|repair) (?:shop|garage)", r"under the hood"],
    "scientist at work": [r"scientists?", r"researchers?", r"lab coat", r"laborator\w+", r"test tubes?", r"pipett?e"],
    "entrepreneur": [r"(?:shop|business|store) owner", r"(?:man|woman) in a suit", r"businessm[ae]n", r"businesswom[ae]n"],
    "accountant at desk": [r"(?:paperwork|documents|papers|calculator|spreadsheets?)", r"(?:sits|sitting|seated) at a desk", r"desk"],
    "lawyer at work": [r"lawyers?", r"judges?", r"court ?room", r"attorneys?", r"(?:at|behind) a podium", r"podium"],
    "farmer at work": [r"farmers?", r"farm ?workers?", r"(?:plow|till|plant|harvest)\w* (?:a|the) (?:field|crop)", r"(?:working|works) in (?:a|the) field"],
    "call center agent": [r"headsets?", r"(?:talks?|talking|speaks?|speaking) on (?:a|the|his|her) (?:phone|telephone)", r"telephone"],
    "delivery driver": [r"delivery", r"(?:truck|van|bus|taxi) drivers?", r"courier", r"mail ?(?:man|carrier)", r"postal worker", r"packages?"],
    "real estate agent": [r"(?:for sale|real estate|open house)", r"house for sale", r"(?:new|model) homes?"],
    # Cities & Urban Life
    "downtown skyline": [r"downtown", r"city ?scape", r"skyline", r"city at (?:night|dusk)", r"aerial view of (?:a|the) city"],
    "pedestrian plaza": [r"plazas?", r"(?:town|city|public) squares?", r"piazza", r"pedestrians?"],
    "urban alley": [r"alley\w*", r"narrow (?:street|lane|passage)s?", r"cobblestone"],
    "metro station": [r"(?:subway|metro|train|underground|railway) (?:station|platform)s?", r"platform"],
    "nightlife district": [r"(?:city|street)s? at night", r"neon (?:signs?|lights)", r"night ?life", r"(?:bars?|pubs?|clubs?) at night", r"illuminated street"],
    "urban rooftop": [r"roof ?tops?", r"(?:from|on) (?:a|the) roof", r"terrace overlooking"],
    "crosswalk intersection": [r"crosswalk", r"intersection", r"(?:crossing|cross) the street", r"traffic lights?", r"zebra crossing"],
    "food truck row": [r"food (?:truck|cart|stall|stand|vendor)s?", r"street food", r"hot dog (?:stand|cart)"],
    "graffiti alley": [r"graffiti", r"spray[- ]paint\w*", r"tagged wall"],
    "waterfront promenade": [r"waterfront", r"promenade", r"boardwalk", r"harbou?r ?front", r"riverfront", r"pier\b", r"embankment"],
    "city bike lane": [r"(?:cycl|bik)\w* (?:on|down|along|through) (?:a|the) (?:city )?(?:street|road|lane)", r"bike lane", r"bicycles? (?:parked|on (?:a|the) street)", r"(?:rides?|riding) (?:a|his|her) bicycle"],
    "busy city street": [r"(?:crowded|bustling|busy) street", r"city street", r"traffic"],
    "city park": [r"(?:city|public|urban) park", r"park\b"],
    "street market": [r"(?:outdoor|open-air|street|flea|night) markets?", r"market ?stalls?", r"market\b", r"bazaar"],
    "residential neighborhood": [r"neighborhood", r"residential street", r"row of houses", r"townhouses?"],
    # Culture & Traditions
    "folk dance": [r"(?:folk|traditional|cultural|group of) dancers?", r"danc(?:e|ers|ing) in traditional"],
    "traditional music": [r"(?:band|musicians|group) (?:perform|play)\w*", r"(?:drummers?|bagpip\w+|fiddl\w+)", r"traditional (?:music|instrument)"],
    "handicrafts": [r"(?:craft|handmade|artisan)\w*", r"basket ?weav\w*", r"baskets?"],
    "street festival": [r"festival", r"(?:street|outdoor) (?:fair|event|celebration)"],
    "cultural ceremony": [r"ceremon\w+", r"ritual", r"(?:monks?|priests?)"],
    "regional cuisine": [r"(?:traditional|local|regional|ethnic) (?:dish|food|meal|cuisine)", r"(?:plate|bowl) of (?:food|stew|noodles)"],
    "artisan market": [r"(?:craft|artisan|handicraft|souvenir) (?:market|stall|fair|shop)s?", r"vendors? (?:sell\w*|display\w*)", r"stalls? (?:sell|display)\w*"],
    "weaving": [r"weav\w+", r"loom", r"spinning (?:wheel|yarn|wool)", r"yarn"],
    "pottery making": [r"potter'?s? wheel", r"potters?\b", r"(?:throw|shap|mold)\w* clay", r"clay"],
    "traditional tea ceremony": [r"tea (?:ceremony|house|set|party)", r"(?:pours?|pouring|serving|drinks?|drinking) tea", r"teapot", r"cups? of tea"],
    "religious festival": [r"(?:religious|church) (?:procession|festival|service|celebration)", r"procession", r"(?:worshipp|pilgrim|devotee)\w*", r"(?:temple|church|mosque) (?:ceremony|interior)"],
    "harvest celebration": [r"pumpkins?", r"(?:harvest|autumn|fall) (?:festival|fair|celebration|display)", r"county fair", r"hay ride"],
    "traditional wedding attire": [r"(?:bride|groom)s?", r"wedding (?:dress|gown|attire|couple)", r"traditional (?:attire|dress|costume|clothing|outfit)", r"kimono", r"sari"],
    "folk instrument making": [r"(?:instrument|violin|guitar) (?:maker|making|workshop|repair)", r"luthier", r"(?:carv|whittl)\w+ (?:wood|a)"],
    "storytelling gathering": [r"(?:sit|sitting|gathered|seated) (?:around|in a circle)", r"campfire", r"(?:reads?|reading) (?:a book )?to (?:a group|children|kids|an audience)", r"audience listen\w*"],
    "traditional architecture": [r"(?:temple|pagoda|shrine|church|cathedral|chapel|monastery)s?"],
    "calligraphy": [r"calligraph\w*", r"(?:writing|writes) with a (?:brush|pen)"],
    # Drinks & Beverages
    "beer": [r"beers?\b", r"(?:pints?|mugs?|glass(?:es)?|bottles?|cans?) of beer", r"brew(?:ery|eries|pub|ing|er|ers)\b", r"ales?\b", r"lagers?", r"(?:taps?|kegs?)\b"],
    "wine": [r"wines?\b", r"(?:red|white|rosé|rose) wine", r"wine ?(?:glass(?:es)?|bottles?|cellar|tasting|barrels?|rack)", r"winer(?:y|ies)", r"champagne", r"sommeliers?"],
    "hot chocolate": [r"hot (?:chocolate|cocoa)", r"cocoa", r"(?:cup|mug) of (?:hot )?(?:chocolate|cocoa)", r"whipped cream"],
    "fruit juice": [r"(?:orange|apple|fruit|fresh|glass of) juice", r"juice"],
    "smoothie": [r"smoothies?", r"blended drink"],
    "sparkling water": [r"sparkling", r"(?:glass|bottle) of water", r"(?:carbonated|mineral) water"],
    "soda": [r"(?:soda|soft drink|cola|coke|pepsi)\w*", r"(?:can|cans|bottle) of (?:soda|cola|pop)"],
    "milkshake": [r"milkshakes?", r"shakes?\b", r"ice cream (?:float|sundae)", r"(?:glass|bottle|carton) of milk"],
    "mocktail": [r"cocktails?", r"(?:colou?rful|fruity|tropical) drinks?", r"drinks? (?:with|garnished)", r"(?:glass|glasses) of (?:red |white )?(?:wine|champagne)"],
    "energy drink": [r"energy drink", r"(?:cans?|aluminum cans?)\b"],
    "bottled water": [r"water bottles?", r"bottles? of water", r"plastic bottles?"],
    "lemonade": [r"lemonade", r"lemons?"],
    "iced coffee": [r"iced (?:coffee|tea|drink)", r"(?:cup|glass) of (?:coffee|latte)", r"latte", r"coffee (?:cup|mug)", r"cappuccino", r"espresso"],
    "herbal infusion": [r"(?:herbal|green|mint|chamomile) tea", r"(?:cup|mug) of tea", r"tea ?cups?"],
    "coconut water": [r"coconuts?"],
    "protein shake": [r"protein", r"shaker bottle"],
    # Events & Celebrations
    "birthday party": [r"birthday", r"(?:cake with|lit) candles", r"blow\w* out (?:the )?candles", r"party hats?"],
    "concert crowd": [r"(?:concert|festival|stadium) (?:crowd|audience)", r"crowd (?:of people )?(?:at|watch\w*|cheer\w*)", r"(?:large|huge|packed) crowd", r"audience"],
    "holiday dinner": [r"(?:christmas|thanksgiving|holiday|festive|family) (?:dinner|meal|feast|table)", r"(?:dinner|dining) table", r"(?:roast(?:ed)? )?turkey"],
    "new year celebration": [r"fireworks?", r"new year", r"sparklers?", r"confetti"],
    "community festival": [r"(?:community|town|local|village) (?:festival|fair|event|gathering|celebration)", r"fair\b", r"carnival", r"fairground"],
    "award ceremony": [r"awards?", r"trophy", r"(?:receiv|present|accept)\w* (?:a|an|the) (?:award|certificate|plaque|medal)", r"graduat\w+", r"medals?"],
    "sports celebration": [r"(?:team|players?|athletes?) celebrat\w*", r"celebrat\w+ (?:a|the) (?:goal|victory|win)", r"(?:raises?|raising) (?:a|the|their) (?:trophy|arms)", r"victory"],
    "baby shower": [r"baby shower", r"(?:newborn|infant|baby)\b", r"pregnant"],
    "anniversary party": [r"anniversary", r"(?:elderly|older) couple", r"(?:toast|toasting|raise their glasses)"],
    "retirement party": [r"retirement", r"farewell", r"(?:office|staff) party", r"(?:cuts?|cutting) (?:a|the) cake", r"sheet cake"],
    "charity gala": [r"gala", r"(?:formal|black-tie) (?:event|dinner|attire)", r"banquet", r"fundrais\w+", r"reception"],
    "block party": [r"block party", r"street party", r"(?:backyard|outdoor) (?:party|barbecue|gathering|picnic)", r"picnic"],
    "cultural parade float": [r"parade", r"floats?\b", r"marching band", r"marchers?"],
    # Fantasy & Science Fiction
    "fantasy castle": [r"(?:fairy[- ]tale|fantasy|disney|magical) castle", r"castle (?:at|on|atop|with) (?:night|a hill|turrets)", r"turrets?"],
    "wizard": [r"wizards?", r"sorcer\w+", r"witch\w*", r"(?:costumed|cosplay\w*) (?:figure|person|man|woman)", r"cosplay\w*"],
    "enchanted forest": [r"(?:misty|mossy|foggy|enchanted|mystical|dense|dark) (?:forest|woods)", r"moss-covered"],
    "alien planet": [r"(?:otherworldly|alien|lunar|martian|surreal) (?:landscape|terrain|surface)", r"(?:rock formations|hoodoos|badlands)"],
    "spaceship": [r"spaceships?", r"space ?(?:craft|shuttle|capsule)", r"(?:rocket|shuttle) (?:on display|exhibit)"],
    "cyberpunk city": [r"neon[- ]lit", r"neon (?:signs?|lights)", r"(?:futuristic|cyberpunk) (?:city|street)", r"city (?:lights )?at night"],
    "futuristic robot": [r"robots?", r"humanoid", r"android"],
    "space station": [r"space station", r"(?:international space station|iss)\b"],
    "portal": [r"(?:stone|ornate|arched) (?:doorway|gateway|archway|arch)", r"doorways?", r"archways?", r"gateway"],
    "fantasy creature": [r"dragons?", r"(?:mythical|mythological) (?:creature|figure|beast)", r"gargoyles?", r"(?:dinosaur|monster) (?:statue|sculpture|model)", r"dinosaurs?"],
    "elf warrior": [r"(?:costumed|armou?red) (?:warrior|figure|man|woman|person|performer)", r"(?:medieval|viking|roman|samurai) (?:warrior|soldier|costume|reenact\w*)", r"reenact\w+"],
    "steampunk machine": [r"steampunk", r"steam (?:engine|locomotive|train|machine)", r"(?:brass|antique|vintage) (?:machine|machinery|mechanism|gears)", r"gears?"],
    "post-apocalyptic wasteland": [r"(?:abandoned|derelict|ruined|decaying|dilapidated) (?:building|factory|house|structure|car|town)s?", r"ruins", r"rubble", r"wreck(?:age|ed)"],
    "underwater fantasy city": [r"underwater", r"(?:submerged|sunken) (?:ruins|ship|statue|structure)", r"scuba ?diver"],
    "floating islands": [r"islands? (?:in|amid|surrounded by) (?:mist|fog|clouds)", r"(?:rocky|small|tiny) islands?", r"islets?", r"sea stacks?"],
    "mech suit": [r"(?:giant|large) robots?", r"exoskeleton", r"armou?r(?:ed)? suit", r"suits? of armou?r", r"armou?r"],
    # Fashion & Apparel
    "evening dress": [r"(?:evening|formal|long|elegant|red|black|white|ball) (?:dress|gown)", r"gowns?"],
    "streetwear": [r"hoodie", r"(?:baseball )?cap and", r"(?:graphic|oversized) t-shirt", r"(?:denim|leather) jacket", r"street (?:style|fashion)"],
    "sportswear": [r"(?:athletic|sports|running) (?:wear|gear|outfit|clothing|jersey|shoes)", r"jerseys?", r"tracksuit"],
    "handbag": [r"(?:hand)?bags?\b", r"purses?", r"backpacks?", r"tote"],
    "scarf and accessories": [r"scar(?:f|ves)", r"sunglasses", r"necklaces?", r"earrings?", r"bracelets?"],
    "formal shoes": [r"(?:leather|dress|formal|high-heeled) shoes", r"high heels", r"heels\b", r"boots"],
    "swimwear": [r"swim\w*", r"bikini", r"bathing suit"],
    "hat collection": [r"hats?\b", r"(?:cowboy|straw|top|fedora|wide-brimmed) hats?", r"caps?\b"],
    "belt and leather goods": [r"leather (?:bag|goods|belt|wallet|jacket|boots|saddle)", r"belts?\b", r"wallets?", r"saddles?"],
    "wristwatch": [r"(?:wrist)?watch(?:es)?\b"],
    # Food & Cooking
    "pasta": [r"pasta", r"spaghetti", r"noodles?", r"lasagna", r"macaroni"],
    "sushi": [r"sushi", r"sashimi", r"japanese (?:dish|food|meal)"],
    "steak": [r"steaks?", r"grilled (?:meat|beef|chicken)", r"beef", r"roast"],
    "tacos": [r"tacos?", r"burritos?", r"tortillas?", r"nachos", r"mexican (?:food|dish)"],
    "curry": [r"curr(?:y|ies)", r"stew", r"indian (?:food|dish|meal)"],
    "rice dish": [r"rice", r"paella", r"risotto", r"fried rice", r"(?:bowl|plate) of rice"],
    "ramen": [r"ramen", r"noodle soup", r"(?:bowl|bowls) of noodles", r"pho\b"],
    "dumplings": [r"dumplings?", r"dim sum", r"buns?\b", r"pierogi", r"empanadas?"],
    "barbecue platter": [r"barbecu\w+", r"bbq", r"grill(?:ing|ed)?\b", r"ribs\b", r"sausages?", r"skewers?", r"kebabs?"],
    "breakfast plate": [r"breakfast", r"(?:fried |scrambled )?eggs", r"pancakes?", r"waffles?", r"bacon", r"toast\b"],
    "seafood platter": [r"seafood", r"shrimp", r"prawns?", r"oysters?", r"mussels?", r"clams?", r"(?:fried|grilled) fish", r"fish (?:and chips|dish|market)"],
    "vegan bowl": [r"(?:salad|grain|poke|buddha|acai) bowl", r"bowl of (?:vegetables|salad|fruit|greens)", r"(?:fresh )?(?:fruit|vegetable) (?:platter|display|stand)"],
    "cheese board": [r"cheese", r"charcuterie", r"(?:platter|board) of (?:meat|cheese|appetizers)", r"appetizers?", r"crackers"],
    "baked pastry": [r"pastr(?:y|ies)", r"croissants?", r"pies?\b", r"tarts?\b", r"muffins?", r"cookies?", r"bread\b", r"loaves", r"bak(?:ery|ed goods)", r"donuts?", r"doughnuts?", r"cakes?\b", r"cupcakes?"],
    "burger": [r"(?:ham|cheese)?burgers?", r"hot ?dogs?", r"fries\b"],
    # History & Vintage
    "antique furniture": [r"antique\w*", r"(?:wooden|ornate|vintage|old) (?:furniture|chair|cabinet|dresser|desk|chest|table)"],
    "old camera": [r"(?:old|vintage|antique|film|old-fashioned) cameras?", r"(?:twin-lens|rangefinder|polaroid|slr) cameras?"],
    "vinyl record player": [r"(?:record|vinyl) (?:player|turntable)", r"turntables?", r"phonograph", r"gramophone", r"jukebox"],
    "historic train": [r"steam (?:train|locomotive|engine)", r"(?:old|vintage|historic|antique) (?:train|locomotive|railway|railroad|tram|trolley|streetcar)s?", r"locomotives?", r"railway carriage"],
    "old factory": [r"(?:old|abandoned|historic|brick|disused) (?:factory|mill|warehouse|plant)s?", r"mill\b", r"smokestacks?", r"chimney stacks?"],
    "vintage fashion": [r"(?:vintage|retro|period|victorian|1920s|1950s|historical) (?:clothing|dress|attire|costume|outfit|fashion)", r"(?:period|historical) costumes?", r"costumes?\b"],
    "antique clock": [r"clocks?", r"clock ?tower", r"pocket watch"],
    "historic aircraft": [r"(?:vintage|old|historic|antique|world war|ww2|wwii|military) (?:aircraft|airplane|plane|biplane|bomber|fighter)s?", r"biplanes?", r"propeller (?:plane|aircraft)", r"(?:bomber|fighter) (?:plane|jet)s?", r"aircraft", r"airplanes?"],
    "old newspaper": [r"newspapers?", r"(?:old|yellowed|aged) (?:documents?|letters?|papers?|book)s?", r"magazines?", r"handwritten (?:letter|note|document)s?"],
    "vintage radio": [r"radios?", r"(?:old|vintage) (?:television|tv|electronics)"],
    "old film projector": [r"projectors?", r"film reels?", r"(?:movie|film) (?:camera|equipment)"],
    "antique map": [r"(?:old|antique|historic|vintage) maps?", r"maps?\b"],
    "historic ship": [r"(?:tall|sailing|old|historic|wooden|pirate) ships?", r"(?:schooner|galleon|frigate|clipper)s?", r"(?:masts|sails|rigging)"],
    "retro diner": [r"diner\b", r"(?:retro|vintage|1950s) (?:restaurant|cafe|interior|decor|sign)", r"(?:soda fountain|lunch counter)", r"neon sign"],
    "vintage toy collection": [r"(?:vintage|antique|old|toy) (?:toys?|dolls?)", r"dolls?\b", r"tin toys?", r"toys?\b"],
    "typewriter": [r"typewriters?", r"type ?setting"],
    "historic street": [r"(?:old|historic|narrow|cobblestone|medieval) (?:streets?|town|quarter|district)"],
    # Household Objects
    "vacuum cleaner": [r"vacuum\w*", r"(?:broom|mop)s?", r"sweeping"],
    "washing machine": [r"washing machines?", r"(?:laundr\w+|dryer)", r"clothes ?line", r"hanging (?:clothes|laundry)"],
    "coffee maker": [r"coffee (?:maker|machine|pot|grinder)", r"espresso machine", r"french press", r"kettle"],
    "kitchen utensils": [r"(?:kitchen )?utensils", r"(?:pots and pans|frying pan|cooking pot|spatula|whisk|ladle|knives|cutlery|silverware)", r"(?:pots|pans)\b"],
    "storage bins": [r"(?:storage )?(?:bins|boxes|crates|baskets|containers)\b", r"cardboard box\w*", r"shelves (?:filled|stocked|lined) with"],
    "dish rack": [r"dishes", r"(?:plates|bowls|cups|mugs|glasses) (?:on|in|stacked)", r"(?:kitchen )?sink", r"(?:washing|washes|drying) (?:the )?dishes"],
    "iron and ironing board": [r"iron(?:ing)?\b", r"ironing board", r"sewing machine", r"(?:folded|folding) (?:clothes|laundry)"],
    "trash can": [r"(?:trash|garbage|rubbish|litter|waste) (?:can|bin|bag|container)s?", r"dumpsters?", r"recycling (?:bin|center|bins)?", r"trash\b", r"garbage\b", r"litter\b"],
    # Human Activities
    "cleaning": [r"clean\w*", r"sweep\w*", r"mop\w*", r"scrub\w*", r"wip(?:e|es|ing) (?:down|the)"],
    "working from home": [r"(?:laptop|computer) (?:at|on) (?:a|the|his|her) (?:kitchen table|couch|sofa|bed|desk at home)", r"(?:at|on) (?:a|the|his|her) (?:couch|sofa|bed) with a laptop", r"home office", r"(?:uses|using|works on) a laptop"],
    "photography": [r"photograph(?:ing|ers?)\b", r"(?:holding|with|uses|using|aims) (?:a|his|her) camera", r"tak(?:es|ing) (?:a )?(?:photo|picture|selfie)s?", r"tripod", r"selfie"],
    "walking a dog": [r"(?:walk|walks|walking) (?:a|his|her|their|the) dogs?", r"dogs? on a leash", r"leash"],
    "camping": [r"camp\w*", r"tents?\b", r"campfire", r"sleeping bags?"],
    "playing chess": [r"chess\w*"],
    "knitting": [r"knit\w*", r"crochet\w*", r"sew(?:s|ing)\b", r"(?:ball of |skeins? of )?yarn"],
    "baking bread": [r"bak(?:es|ing|er)\b", r"kneading", r"dough", r"(?:loaves|loaf) of bread", r"(?:freshly )?baked bread", r"bread"],
    "woodworking": [r"woodwork\w*", r"carpent\w+", r"(?:sawing|carving|sanding|planing) (?:a )?(?:wood|plank|board)", r"workbench", r"workshop", r"lumber"],
    "meditating": [r"meditat\w+", r"yoga", r"lotus position", r"(?:cross-legged|with (?:eyes|her eyes|his eyes) closed)"],
    "dancing at home": [r"danc(?:e|es|ing|ers?)\b"],
    "playing board games": [r"(?:board|card|dice|table(?:top)?) games?", r"(?:playing|play) (?:a )?(?:game|cards)", r"(?:dominoes|mahjong|checkers|backgammon|puzzle)"],
    "washing a car": [r"car wash", r"(?:wash|washes|washing|clean\w*|polish\w*) (?:a|the|his|her) (?:car|vehicle|truck)"],
    "assembling furniture": [r"(?:assembl|build|construct)\w* (?:a|the) (?:shelf|desk|table|chair|cabinet|bookshelf|furniture|bed)", r"(?:power )?drill\w*", r"screw\w*", r"hand ?tools?", r"diy\b"],
    "gardening": [r"garden\w*", r"(?:plant|water|prun|weed)\w* (?:a|the|some)? ?(?:plants|flowers|garden|seedlings|tree)", r"potting"],
    # Industrial & Engineering
    "factory production line": [r"(?:production|assembly|manufacturing|bottling) (?:line|plant|floor|facility)", r"factory", r"conveyor"],
    "CNC machine": [r"(?:cnc|lathe|milling machine|machining|machine shop|machinist)", r"(?:industrial|heavy) machinery", r"machinery"],
    "industrial robot arm": [r"robot(?:ic)? arms?", r"industrial robots?", r"automat(?:ed|ion)"],
    "construction crane": [r"construction (?:site|crane|workers?|equipment)", r"cranes? (?:tower|lift|above|over|at)", r"(?:tower|construction) cranes?", r"excavators?", r"bulldozers?", r"scaffold\w*"],
    "solar farm": [r"solar (?:panels?|farm|array|power)"],
    "oil refinery": [r"refiner(?:y|ies)", r"(?:oil|gas) (?:rig|platform|well|pump|tanks?|plant)", r"pump ?jacks?", r"storage tanks", r"petrochemical"],
    "power station": [r"power (?:plant|station|lines?)", r"cooling towers?", r"(?:nuclear|coal|hydroelectric|hydro) (?:plant|station|dam)", r"\bdams?\b", r"transmission (?:towers?|lines)", r"pylons?", r"smokestack"],
    "data center": [r"data ?cent(?:er|re)", r"servers?\b", r"(?:network|computer) (?:equipment|room|cables)", r"cables"],
    "laboratory equipment": [r"(?:lab|laboratory) (?:equipment|bench|glassware|instruments?)", r"beakers?", r"flasks?", r"test tubes?", r"petri dish\w*", r"centrifuge", r"pipett?es?"],
    "mechanical gears": [r"gears?\b", r"cogs?\b", r"(?:engine|machine|mechanical) (?:parts|components|mechanism)", r"engines?\b", r"pistons?"],
    "assembly line workers": [r"(?:factory|industrial|assembly|production) workers?", r"workers? (?:in|at) (?:a|the) (?:factory|plant|assembly)", r"hard ?hats?", r"welding"],
    "shipping container yard": [r"(?:shipping|cargo) containers?", r"container (?:ship|port|terminal|yard)", r"(?:port|harbou?r) cranes?", r"(?:cargo|shipping) port"],
    "steel mill": [r"steel (?:mill|plant|works|beams?|factory)", r"(?:molten|hot) (?:metal|steel|iron)", r"foundry", r"blast furnace", r"forge\b", r"blacksmith\w*", r"sparks? fly"],
    "pipeline infrastructure": [r"pipe ?lines?", r"(?:large|industrial|metal|steel) pipes?", r"pipes\b", r"valves?"],
    "3D printing factory floor": [r"3d print\w*", r"(?:prototype|prototyping|fabrication) (?:lab|workshop|machine)", r"(?:maker ?space|fab ?lab)"],
    "electrical substation": [r"(?:electrical|power) (?:substation|grid|transformers?|equipment|infrastructure)", r"substation", r"transformers?", r"(?:high-voltage|power) lines?", r"utility poles?", r"electrical"],
    "wind turbine": [r"wind ?(?:turbines?|farm|mills?)", r"windmills?"],
    # Insects & Small Creatures
    "ladybug": [r"lady ?(?:bug|bird|beetle)s?", r"beetles?"],
    "praying mantis": [r"mantis\w*", r"mantid\w*", r"stick insects?", r"katydids?"],
    "firefly": [r"fireflies", r"firefly", r"glow ?worms?", r"(?:night|nocturnal) insects?", r"moths?\b"],
    "centipede": [r"centipedes?", r"millipedes?", r"worms?\b", r"earthworms?", r"slugs?\b"],
    "grasshopper": [r"grasshoppers?", r"crickets?", r"locusts?", r"cicadas?"],
    "ant": [r"ants?\b", r"termites?"],
    "snail": [r"snails?", r"slugs?", r"shells? on"],
    "wasp": [r"wasps?", r"hornets?", r"(?:honey ?)?bees?\b", r"bumble ?bees?"],
    # Interiors & Rooms
    "minimalist bedroom": [r"bedrooms?", r"(?:neatly )?made bed", r"(?:a|the) bed (?:with|and)", r"beds?\b"],
    "luxury kitchen": [r"kitchens?", r"(?:kitchen )?(?:island|countertops?|cabinets)"],
    "home office": [r"(?:home )?office\b", r"(?:desk|workspace) (?:with|and) (?:a )?(?:computer|laptop|monitor|lamp)", r"study room"],
    "coffee shop interior": [r"(?:coffee ?shop|caf[eé]|coffeehouse)s?", r"(?:barista|espresso bar)"],
    "hotel room": [r"hotel (?:room|suite|bed)", r"guest ?room"],
    "hotel lobby": [r"(?:hotel )?lobby", r"(?:grand|ornate|spacious) (?:hall|foyer|atrium|entrance)", r"atrium", r"foyer"],
    "library interior": [r"librar(?:y|ies)", r"(?:shelves|rows) (?:of|filled with|lined with) books", r"bookshelves", r"reading room"],
    "gym interior": [r"\bgym(?:nasium)?\b", r"fitness (?:center|studio|class|room)", r"(?:treadmills?|exercise (?:machines|equipment|bikes?)|dumbbells?|barbells?|weights)"],
    "nursery room": [r"nursery", r"(?:crib|cradle|baby'?s? room|playroom|children'?s? room)", r"(?:toddler|baby|infant) (?:plays|playing|sits|sitting|in)"],
    "walk-in closet": [r"closets?", r"wardrobes?", r"(?:clothes|garments|dresses|shirts) (?:hang|hanging|on hangers|on a rack)", r"clothing (?:store|rack|boutique|shop)", r"boutique"],
    "attic space": [r"attics?", r"(?:sloped|slanted|beamed|exposed wooden) (?:ceiling|roof|beams)", r"loft\b", r"(?:wooden )?beams"],
    "basement lounge": [r"basement", r"cellar", r"(?:bar|lounge|pub|tavern|club) interior", r"lounge", r"(?:pool|billiard)s? table", r"billiards?", r"bar\b", r"pub\b"],
    "art studio interior": [r"(?:art|artist'?s?|painting|pottery|sculpture) (?:studio|workshop|class)", r"easels?", r"(?:paints?|paintbrush\w*|brushes) (?:on|and)", r"(?:artist|painter)s? (?:at work|paint\w*|work\w*)"],
    "spa interior": [r"\bspa\b", r"(?:indoor )?(?:swimming )?pools?", r"sauna", r"(?:massage|treatment) (?:room|table)", r"bath\s?(?:tub|house|room)s?"],
    "restaurant interior": [r"restaurants?", r"(?:dining|eating) (?:area|hall|room)", r"(?:tables|diners)"],
    "modern living room": [r"living room", r"(?:couch|sofa|armchair)s?", r"fireplace"],
    # Maps & Cartography
    "world map": [r"(?:map|maps) of the world", r"world maps?"],
    "city street map": [r"(?:city|street|town|tourist|wall|information|directory) maps?", r"maps?\b", r"(?:information|tourist) (?:board|sign)"],
    "topographic map": [r"(?:topographic|relief|terrain|contour) (?:map|model)s?", r"(?:scale|terrain|landscape) models?", r"diorama"],
    "nautical chart": [r"(?:nautical|navigation\w*) (?:chart|instruments?)", r"compass\w*", r"sextants?", r"(?:ship'?s? )?(?:wheel|helm)", r"lighthouses?"],
    "subway transit map": [r"(?:subway|metro|transit|train|bus|rail) (?:map|sign|signs|signage|schedule|timetable|route)", r"(?:departure|arrival) board", r"(?:station|platform) signs?"],
    "hiking trail map": [r"trail (?:map|sign|marker|head)s?", r"(?:signpost|sign post|trailhead|wooden sign|directional sign)s?", r"(?:hiking|walking) (?:trail|path)s?"],
    "satellite map view": [r"aerial (?:view|photo|shot|image)", r"(?:bird'?s?-eye|overhead|drone) view", r"(?:from|seen from) above", r"from (?:an|a) (?:airplane|plane|aircraft) window"],
    "weather map": [r"weather (?:station|instruments?|vane|balloon|radar|forecast)", r"(?:anemometer|barometer|thermometer|weathervane)s?"],
    "road atlas page": [r"(?:road|highway|street|traffic|direction) signs?", r"(?:highway|interstate|freeway|motorway)s?", r"(?:winding|open|empty|long) road", r"road ?trip"],
    "treasure map style": [r"(?:treasure|pirate) (?:map|chest|ship)", r"(?:old|aged|rolled|parchment) (?:scroll|parchment|map)", r"scrolls?\b", r"parchment", r"treasure"],
    "globe": [r"globes?\b"],
    # Marine Life
    "great white shark": [r"sharks?"],
    "blue whale": [r"whales?", r"humpback\w*"],
    "orca": [r"orcas?", r"killer whales?", r"belugas?", r"porpoises?"],
    "sea turtle": [r"sea turtles?", r"turtles? swim\w*", r"(?:green|loggerhead|hawksbill) turtles?"],
    "octopus": [r"octop(?:us|i|uses)", r"squids?", r"cuttlefish"],
    "seahorse": [r"seahorses?", r"sea horses?", r"(?:aquarium|tank) (?:fish|display)", r"aquarium"],
    "stingray": [r"(?:sting|manta|eagle)? ?rays?\b", r"skates?\b"],
    "coral reef fish": [r"coral (?:reef|reefs)?", r"reef\b", r"(?:tropical|colou?rful|school of) fish", r"fish (?:swim\w*|in (?:an|the) aquarium)", r"schools? of fish"],
    "clownfish": [r"clown ?fish", r"(?:tropical|orange|colou?rful) fish", r"anemone ?fish"],
    "manta ray": [r"manta\w*"],
    "sea otter": [r"(?:sea |river )?otters?", r"beavers?", r"muskrats?"],
    "hammerhead shark": [r"hammerheads?", r"sharks?"],
    "eel": [r"eels?\b", r"moray\w*"],
    "anemone": [r"anemones?", r"(?:sea )?(?:urchins?|stars?|starfish)", r"tide ?pools?", r"coral"],
    "walrus": [r"walrus\w*", r"(?:elephant )?seals?\b"],
    "sea lion": [r"sea lions?", r"seals?\b"],
    "crab": [r"crabs?", r"crayfish", r"shrimp"],
    "jellyfish": [r"jelly ?fish", r"jellies"],
    "dolphin": [r"dolphins?"],
    # Media & Entertainment
    "cinema theater": [r"(?:movie|cinema|film) (?:theat(?:er|re)|screen|screening|poster)", r"cinema", r"theat(?:er|re) (?:seats|interior|marquee|auditorium)", r"marquee", r"auditorium"],
    "film camera": [r"(?:film|movie|video|cine) cameras?", r"camera ?(?:crew|operator|man)", r"(?:filming|film crew|cameraman)"],
    "music concert": [r"concerts?", r"(?:band|musicians?|singers?) (?:perform|play|sing)\w*", r"(?:on|a) stage", r"live (?:music|performance|band)", r"(?:rock|jazz) band"],
    "recording studio": [r"(?:recording|music|sound) studio", r"(?:mixing|sound) (?:board|desk|console)", r"microphones?"],
    "DJ setup": [r"\bdjs?\b", r"(?:turntables?|mixer|decks)", r"disc jockey"],
    "video game setup": [r"video ?games?", r"gaming", r"(?:game )?controllers?", r"(?:playing|plays) (?:a )?(?:video ?game|games)", r"consoles?"],
    "arcade": [r"arcade\w*", r"pinball", r"slot machines?", r"casino"],
    "stage performance": [r"(?:performs?|performing|performers?|actors?|actresses?) (?:on|at)", r"(?:theat(?:er|re)|stage) (?:performance|production|play|show)", r"perform\w*", r"(?:ballet|dance) (?:performance|dancers?)"],
    "podcast studio": [r"podcast\w*", r"(?:radio|broadcast) (?:studio|station|booth|host)", r"(?:microphone|mic)s?\b", r"interview\w*"],
    "television studio": [r"(?:tv|television|news|broadcast) (?:studio|set|crew|camera|anchor|presenter|reporter|interview)", r"(?:reporters?|journalists?|news crew)", r"televisions?"],
    "book collection": [r"books?\b", r"bookstores?", r"(?:stack|pile|shelves|rows) of books", r"(?:reading|reads) a book"],
    "movie set": [r"(?:movie|film) (?:set|shoot|production|crew)", r"(?:film|camera) crew", r"(?:filming|behind the scenes)", r"lighting equipment"],
    "orchestra performance": [r"orchestras?", r"symphon\w+", r"(?:string|brass) (?:quartet|ensemble|section)", r"ensemble", r"conductor", r"choirs?\b"],
    "comedy club stage": [r"comedians?", r"(?:stand-up|comedy|open mic)", r"(?:speaks?|speaking|holding) (?:into )?a microphone", r"(?:speaker|presenter) on (?:a|the) stage", r"(?:on|at) (?:a|the) podium", r"presentation"],
    "street performer": [r"street (?:performers?|musicians?|artists?|performance|entertainers?)", r"busk(?:er|ers|ing)", r"juggl\w+", r"mimes?\b", r"(?:clowns?|acrobats?|fire (?:dancer|breather)s?|stilt walkers?)", r"(?:performs?|performing|plays?|playing) (?:on|in) the street"],
    "vinyl record collection": [r"(?:vinyl )?records?\b", r"(?:vinyl|lp|album)s?\b", r"record (?:store|shop|collection)", r"cds?\b"],
    "theater backstage": [r"backstage", r"(?:dressing room|behind the stage|curtains?)", r"(?:rehears\w+)", r"(?:costumed|in costume)"],
    "board game": [r"board ?games?", r"chess", r"dice"],
    # Medicine & Healthcare
    "hospital room": [r"hospital", r"(?:patient|hospital) (?:bed|ward|room)", r"(?:patients?|ward)\b"],
    "doctor consultation": [r"doctors?", r"physicians?", r"(?:medical|clinic) (?:exam\w*|appointment|consultation|check-?up)", r"(?:examin\w+|check\w*) (?:a|the) patient", r"patients?"],
    "nurse at work": [r"nurses?", r"(?:health ?care|medical) (?:workers?|staff|professionals?|personnel|team)", r"(?:scrubs|medical uniform)", r"caregivers?", r"paramedics?"],
    "medical laboratory": [r"(?:medical|clinical|hospital|research) (?:lab|laboratory)", r"(?:lab|laboratory) (?:technician|worker|coat)", r"(?:blood|tissue|lab) samples?", r"microscopes?", r"test tubes?", r"laborator\w+"],
    "field medic training": [r"(?:combat |army |military |field )?medics?\b", r"(?:medical|first aid|trauma|casualty|triage) (?:training|exercise|drill|evacuation)", r"(?:simulated|mock) (?:casualt\w+|patient|injur\w+)", r"(?:treats?|treating|tends? to) (?:a|an|the) (?:wounded|injured) ", r"medevac"],
    "X-ray equipment": [r"x-?rays?", r"radiolog\w+", r"(?:medical|hospital) (?:equipment|machine|device)s?"],
    "surgical instruments": [r"surg(?:ery|eon|eons|ical)", r"operating (?:room|table|theat(?:er|re))", r"scalpels?", r"(?:medical|dental) (?:instruments|tools)"],
    "dentist office": [r"dent(?:ist|al)\w*", r"(?:teeth|tooth)", r"orthodont\w+"],
    "physical therapy": [r"(?:physical )?therap\w+", r"rehabilitat\w+", r"(?:stretch|exercis)\w+ (?:with|band)", r"wheelchairs?", r"crutches"],
    "vaccination clinic": [r"vaccin\w+", r"(?:inject\w*|syringes?|needles?|shots?\b|immuniz\w+)", r"clinic\b", r"(?:health|medical) (?:clinic|center|centre|camp)"],
    "emergency room": [r"emergency", r"(?:ambulances?|stretchers?|gurneys?|paramedics?|first aid|rescue workers?|triage)"],
    "medical imaging screen": [r"(?:medical|monitor|screen)s? (?:display\w*|show\w*)", r"(?:heart|vital signs?|patient) monitors?", r"ultrasound", r"(?:medical|hospital) (?:monitors?|screens?|displays?)"],
    "home healthcare visit": [r"(?:elderly|older|senior|aged) (?:woman|man|people|person|patient|couple|residents?)", r"(?:caregiver|carer|home care|nursing home|assisted living)", r"(?:grand(?:mother|father|parents?))"],
    "mental health counseling session": [r"counsel\w+", r"(?:sit|sitting|seated) (?:across from|facing|opposite) (?:each other|one another)", r"(?:conversation|talking|chatting|discussion) (?:between|with) (?:two|a)", r"support group", r"(?:two (?:men|women|people)) (?:talk|converse|chat)\w*"],
    "childbirth ward": [r"(?:newborn|new-born)s?", r"(?:holds?|holding|cradl\w+) (?:a|an|her|his|their) (?:newborn|baby|infant)", r"(?:mother|parents?) (?:with|and|holding) (?:a|her|their) (?:baby|newborn|infant)", r"maternity", r"(?:babies|baby|infant)\b"],
    "stethoscope": [r"stethoscopes?"],
    "pharmacy": [r"pharmac(?:y|ies|ist)", r"(?:pills?|tablets? and|capsules|medication|medicine)s?", r"drugstore"],
    # Musical Instruments
    "synthesizer keyboard": [r"synth\w*", r"(?:electronic|digital|electric) (?:keyboard|piano|organ)", r"keyboards?", r"(?:modular|analog) (?:system|synth)", r"organ\b"],
    "drum kit": [r"drums?\b", r"drummers?", r"drum ?kit", r"cymbals?", r"percussion"],
    "double bass": [r"(?:double|upright|stand-up) bass", r"bass\b", r"bassists?", r"contrabass"],
    "harp": [r"harps?\b", r"harpists?", r"lyre"],
    "ukulele": [r"ukuleles?", r"banjos?", r"mandolins?"],
    "cello": [r"cell(?:o|os|ist|ists)\b", r"violas?", r"violins?", r"fiddle"],
    # Nature & Landscapes
    "ocean coast": [r"coast\w*", r"shore\w*", r"(?:sea|ocean) ?(?:side|view|waves|front)", r"(?:rocky|sandy) beach", r"waves crash\w*", r"ocean\b", r"beach\b"],
    "glacier": [r"glaciers?", r"ice ?(?:field|berg|cap|sheet)s?", r"snow-capped"],
    "volcano": [r"volcan\w+", r"lava", r"crater", r"geysers?"],
    "tropical island": [r"tropical", r"palm trees?", r"(?:turquoise|crystal[- ]clear) (?:water|sea|ocean)", r"islands?"],
    "savanna": [r"savann?ah?", r"grasslands?", r"prairie", r"(?:african|open) plains?", r"plains\b", r"meadows?"],
    "fjord": [r"fjords?", r"(?:mountain|glacial|alpine) (?:valley|lake|lakes)", r"lake surrounded by mountains", r"(?:steep|rugged) (?:mountains|cliffs) (?:rise|surround)"],
    "cliff coastline": [r"cliffs?", r"(?:rocky|rugged|steep) (?:coast|coastline|shore|headland|bluffs?)", r"sea stacks?", r"bluffs?\b"],
    "sand dunes": [r"(?:sand )?dunes?", r"deserts?\b"],
    "alpine lake": [r"(?:alpine|mountain|glacial|calm|still|tranquil|serene) lakes?", r"lakes?\b", r"(?:mountain )?reflect\w+ (?:in|on) (?:a|the) (?:lake|water)"],
    "rainforest canopy": [r"rain ?forests?", r"jungle", r"(?:lush|dense|tropical) (?:vegetation|forest|foliage|greenery)", r"(?:forest|tree) canopy"],
    "salt flat": [r"salt (?:flat|pan|lake|marsh)s?", r"(?:dry|cracked) (?:lake ?bed|earth|mud|ground)", r"(?:barren|arid|desolate) (?:landscape|terrain|plain)"],
    "wetland": [r"wetlands?", r"marsh\w*", r"swamps?", r"bogs?\b", r"pond\b"],
    # People & Portraits
    "adult man portrait": _portrait(r"(?:man|gentleman|guy)"),
    "adult woman portrait": _portrait(r"(?:woman|lady)"),
    "elderly adult portrait": _portrait(r"(?:elderly|older|old|senior|aged|gray-haired|white-haired) (?:man|woman|person|gentleman|lady)") + [r"(?:elderly|older|senior) (?:man|woman|person|people)"],
    "young adult portrait": _portrait(r"(?:young (?:man|woman|adult|person)|teenager|student)") + [r"young (?:man|woman)"],
    "adult couple portrait": [r"(?:a|the) couple", r"(?:man and (?:a )?woman|husband and wife|bride and groom)", r"couple\b"],
    "adult family group": [r"famil(?:y|ies)", r"(?:parents?|mother|father) (?:and|with) (?:their|her|his|two|three)? ?(?:children|kids|sons?|daughters?)", r"(?:mother|father|mom|dad) (?:and|with)"],
    "adult friends group": [r"(?:group|trio|pair) of (?:friends|young people|people|men|women|adults)", r"friends\b", r"(?:three|four|five|several) (?:people|men|women|friends|young)"],
    "artist portrait": [r"(?:artist|painter|sculptor|potter|illustrator)s?\b"],
    "musician portrait": [r"musicians?", r"(?:guitarist|singer|violinist|pianist|drummer|saxophonist|trumpeter|cellist|bassist|vocalist)s?"],
    "athlete portrait": [r"athletes?", r"(?:runner|player|cyclist|swimmer|boxer|gymnast|skier|footballer|wrestler|sprinter)s?\b"],
    "chef portrait": [r"chefs?\b", r"(?:cooks?|bakers?)\b"],
    "adult teacher portrait": [r"teachers?", r"(?:professor|instructor|lecturer|educator|tutor)s?", r"teach\w+"],
    "adult doctor portrait": [r"(?:doctors?|physicians?|surgeons?)", r"white coat"],
    "adult scientist portrait": [r"scientists?", r"researchers?", r"lab coats?", r"(?:chemist|biologist|physicist|engineer|astronomer)s?"],
    "adult farmer portrait": [r"farmers?", r"(?:rancher|cowboy|shepherd|herder|fisherman|fishermen)s?"],
    "adult firefighter portrait": [r"fire ?fight\w+", r"firem[ae]n", r"fire (?:truck|engine|department|crew|station)", r"(?:rescue|emergency) (?:workers?|crews?|personnel)"],
    "adult police officer portrait": [r"police\w*", r"(?:law enforcement|sheriff|state trooper|trooper|patrol)", r"officers?\b", r"(?:security )?guards?\b", r"soldiers?"],
    "adult chef in kitchen portrait": [r"(?:chef|cook)s? (?:in|at|stand\w*|work\w*|prepar\w*)", r"(?:in|at) (?:a|the) (?:restaurant |commercial )?kitchen"],
    "adult construction worker portrait": [r"(?:construction|road|building) workers?", r"hard ?hats?", r"(?:workers?|laborers?) (?:in|wearing|build\w*|on)", r"workers?\b", r"(?:safety|high-visibility|hi-vis|reflective) (?:vest|jacket)s?"],
    "adult grandparent portrait": [r"grand(?:mother|father|ma|pa|parents?|children|son|daughter|kids?)", r"(?:elderly|older) (?:man|woman|couple) (?:with|and) (?:a )?(?:child|children|kids|young)"],
    "adult twins portrait": [r"twins?\b", r"(?:two|identical) (?:sisters|brothers|girls|boys)", r"(?:sisters|brothers|siblings)"],
    # Pets & Domestic Animals
    "domestic cat": [r"cats?\b", r"feline"],
    "poodle": [r"poodles?", r"(?:small|fluffy|white|curly) dogs?", r"(?:terrier|chihuahua|pug|shih tzu|dachshund|schnauzer|spaniel|corgi|bulldog)s?"],
    "hamster": [r"hamsters?", r"(?:mice|mouse|rats?|gerbils?|chinchillas?)\b"],
    "guinea pig": [r"guinea pigs?", r"(?:rabbits?|bunn(?:y|ies))"],
    "beagle": [r"beagles?", r"(?:hounds?|basset|jack russell|labrador|husky|huskies|retriever|collie|dogs?)\b"],
    "ferret": [r"ferrets?", r"weasels?", r"(?:minks?|stoats?|martens?)"],
    "pony": [r"ponies", r"pony", r"(?:foals?|donkeys?|mules?|horses?)\b"],
    "pig": [r"pigs?\b", r"piglets?", r"hogs?\b", r"swine", r"sows?\b"],
    "goldfish": [r"goldfish", r"(?:koi|carp)\b", r"fish (?:tank|bowl|pond)", r"(?:koi|fish) pond", r"aquarium"],
    "budgerigar": [r"budgies?", r"budgerigars?", r"parakeets?", r"(?:caged|pet) birds?", r"lovebirds?", r"cockatiels?", r"canar(?:y|ies)"],
    "puppy": [r"pupp(?:y|ies)"],
    # Plants & Botany
    "maple tree": [r"maple\w*", r"(?:autumn|fall) (?:tree|foliage|colors|colours)", r"(?:red|orange|golden) (?:leaves|foliage)", r"(?:oak|birch|willow|elm|beech|chestnut|cherry) trees?", r"(?:large|tall|old|lone|single) trees?"],
    "lavender field": [r"lavender", r"(?:field|fields|meadow) of (?:flowers|wildflowers|poppies|tulips)", r"(?:flower|tulip|poppy) fields?", r"(?:purple|violet) flowers"],
    "bonsai tree": [r"bonsai", r"(?:potted|small|miniature) (?:tree|plant)s?", r"(?:japanese|zen) garden"],
    "lily flower": [r"lil(?:y|ies)", r"(?:orchid|tulip|rose|daisy|daisies|iris|magnolia|lotus|peony|peonies|dahlia|hibiscus)\w*", r"(?:pink|white|red|yellow|purple) flowers?", r"blossoms?", r"flowers?\b"],
    "ivy vine": [r"ivy", r"vines?\b", r"(?:climbing|creeping) plants?", r"moss\b", r"(?:overgrown|covered) with (?:plants|vegetation|greenery|vines)"],
    "mushroom fungi": [r"mushrooms?", r"fung(?:us|i)", r"toadstools?", r"lichen"],
    "seed pod": [r"seed ?(?:pods?|heads?)", r"seeds?\b", r"(?:pine ?cones?|acorns?|dandelion|thistle|milkweed|nuts?)\b", r"berr(?:y|ies)"],
    "vegetable garden": [r"vegetable (?:garden|patch|plot)", r"(?:community|allotment|kitchen) gardens?", r"(?:raised beds?|garden beds?)", r"(?:tomato|pepper|squash|lettuce|cabbage|bean)(?:es|s)? plants?"],
    # Reptiles & Amphibians
    "chameleon": [r"chameleons?", r"(?:green|colou?rful) lizards?", r"anoles?"],
    "iguana": [r"iguanas?", r"(?:large|green|marine) lizards?"],
    "gecko": [r"geckos?", r"(?:small|tiny) lizards?", r"skinks?", r"lizards?"],
    "toad": [r"toads?", r"frogs?", r"bullfrogs?"],
    "crocodile": [r"crocodiles?", r"caimans?", r"gharials?"],
    "tortoise": [r"tortoises?", r"(?:giant|land) turtles?"],
    "salamander": [r"salamanders?", r"newts?", r"axolotls?"],
    "komodo dragon": [r"komodo", r"monitor lizards?", r"(?:large|big|giant) lizards?"],
    "bearded dragon lizard": [r"bearded dragons?", r"(?:spiny|horned|desert|collared) lizards?", r"lizards? (?:bask\w*|rest\w*|sit\w*|perch\w*) on", r"agamas?"],
    "tree frog": [r"tree ?frogs?", r"(?:green|red-eyed|poison dart|colou?rful) frogs?", r"frogs? (?:on|perched|clinging)"],
    "alligator": [r"alligators?", r"gators?"],
    # Science & Education
    "chemistry lab": [r"chemi(?:stry|cal|cals|st|sts)", r"(?:beakers?|flasks?|test tubes?)", r"(?:lab|laboratory) (?:bench|class|experiment|equipment)"],
    "physics experiment": [r"(?:physics|science) (?:experiment|demonstration|lab|class|equipment|exhibit)", r"experiments?\b", r"(?:circuits?|magnets?|lasers?|pendulums?|prisms?)", r"(?:tesla coil|particle accelerator|oscilloscope)"],
    "biology lab": [r"biolog\w+", r"(?:specimens?|dissect\w*|petri dish\w*|microscope slides?)", r"(?:lab|laboratory) (?:workers?|technicians?|coats?)", r"(?:skeleton|fossil)s?"],
    "astronomy observatory": [r"observator(?:y|ies)", r"(?:telescope|observatory) dome", r"planetarium", r"radio (?:telescope|dish|antenna)s?", r"satellite dish\w*"],
    "classroom": [r"class ?rooms?", r"(?:students?|pupils|children|kids) (?:sit\w*|seated|at (?:their )?desks|in class|listen\w*|learn\w*|study\w*|rais\w*)", r"(?:school ?children|school ?kids|students)", r"blackboard", r"chalkboard", r"whiteboard"],
    "university lecture hall": [r"lecture\w*", r"(?:auditorium|seminar|conference hall)", r"(?:university|college) (?:students?|class|campus|hall)", r"(?:audience|attendees) (?:listen\w*|seated|sit\w*)", r"(?:speaker|presenter|professor) (?:address\w*|speak\w*|present\w*)"],
    "textbooks": [r"textbooks?", r"(?:open|stack of|pile of|reading a|reads a|holding a) (?:books?|notebooks?)", r"(?:study|studies|studying|homework)", r"notebooks?", r"books?\b"],
    "mathematics notes": [r"(?:math|mathematics|equations?|formulas?|calculations?|numbers)", r"(?:written|writing|writes) on (?:a|the) (?:board|blackboard|chalkboard|whiteboard)", r"(?:handwritten|hand-written) (?:notes?|text)", r"notes\b"],
    "geology samples": [r"(?:rocks?|minerals?|crystals?|gems?|gemstones?|fossils?|geolog\w+|stones?)\b", r"(?:rock|stone) (?:formation|layers|strata|samples?|collection)"],
    "robotics project": [r"robot\w*", r"(?:electronics|electronic components|circuit boards?|arduino|raspberry pi|wiring)", r"(?:engineering|stem|science) (?:project|students?|competition|fair)"],
    "genetics lab": [r"(?:dna|genetic\w*|genom\w+|biotech\w*)", r"(?:lab|laboratory|research|medical) (?:workers?|technicians?|scientists?|researchers?|samples?|equipment)", r"(?:gloved|gloves) hands?"],
    "environmental field research": [r"(?:researchers?|scientists?|biologists?|students?|volunteers?) (?:in|on|at|collect\w*|measur\w*|study\w*|survey\w*|examin\w*|sampl\w*)", r"(?:field ?work|field research|field trip|survey)", r"(?:measuring|collecting|sampling|monitoring) (?:water|soil|plants|samples|data)", r"(?:rangers?|conservation\w*)"],
    "coding classroom": [r"(?:computer|coding|programming|it) (?:lab|class|classroom|room|workshop)", r"(?:rows of|several|multiple) computers", r"(?:students?|people|children|kids) (?:at|using|on|work\w* on) (?:computers|laptops)", r"hackathon"],
    "science fair project": [r"science (?:fair|project|exhibit|museum|festival|show|center)", r"(?:poster|project|research) (?:presentation|board|session|display)s?", r"(?:exhibit|display) (?:booth|table)s?", r"(?:museum|exhibition) (?:visitors|exhibit|display)"],
    "library study session": [r"(?:librar(?:y|ies)|reading room)", r"(?:studying|study|reads?|reading) (?:at|in) (?:a|the) (?:table|desk|library)", r"(?:students?) (?:study\w*|read\w*|work\w*)", r"(?:reads?|reading) (?:a book|books)"],
    "engineering workshop": [r"(?:engineering|mechanical|machine|metal|repair) (?:workshop|shop|lab)", r"(?:engineers?|technicians?|machinists?|mechanics?)", r"workshop", r"(?:welding|soldering|machining)"],
    "microscope": [r"microscopes?"],
    "telescope": [r"telescopes?", r"binoculars"],
    # Space & Astronomy
    "planet surface": [r"(?:lunar|moon|martian|mars|rocky|barren|cratered) (?:surface|landscape|terrain)", r"(?:full |crescent |half )?moon\b", r"craters?"],
    "solar eclipse": [r"eclipse\w*", r"(?:partial|total) eclipse", r"(?:sun|moon) (?:partially )?(?:obscured|covered|blocked)"],
    "space telescope": [r"(?:space|orbiting|hubble|james webb) telescopes?", r"(?:satellite|probe|spacecraft) (?:model|replica|in (?:a|the) (?:clean ?room|museum|hangar|exhibit))", r"satellites?\b"],
    "space station exterior": [r"(?:international )?space station", r"(?:solar|space) (?:arrays?|panels?) (?:in|of) (?:space|orbit)", r"(?:in|from) (?:space|orbit)", r"(?:earth|planet) (?:seen|viewed) from (?:space|orbit)"],
    "meteor shower": [r"meteors?", r"shooting stars?", r"star ?trails?", r"(?:night sky|starry sky) (?:with|filled)"],
    "star cluster": [r"(?:star )?clusters?", r"(?:stars|star-filled|starry) (?:sky|night|field)", r"stars\b", r"constellations?", r"(?:night|dark) sky"],
    "mars rover": [r"rovers?", r"(?:lunar|mars|planetary|space) (?:vehicle|lander|module|exploration)", r"landers?", r"(?:nasa|jpl) (?:engineers?|scientists?|lab|facility|clean ?room)"],
    "sun and solar flare": [r"(?:the )?sun\b", r"sunbeams?", r"sunburst", r"(?:solar|sun) (?:flare|rays?|glare|disk|halo)", r"(?:bright|blazing|glowing) sun"],
    "galaxy": [r"galax(?:y|ies)", r"milky way"],
    "nebula": [r"nebula\w*", r"(?:colou?rful|cosmic|interstellar) (?:clouds?|gas|dust)", r"(?:deep[- ]space|astrophoto\w*)"],
    # Sports & Fitness
    "surfing": [r"surf\w*", r"(?:big|large|crashing|breaking) waves?", r"(?:bodyboard|paddleboard|wakeboard|kitesurf|windsurf)\w*"],
    "skateboarding": [r"skate\w*", r"(?:bmx|scooter|roller ?blad\w*|inline skat\w*)"],
    "rock climbing": [r"climb\w*", r"(?:boulder\w*|rappel\w*|abseil\w*)", r"(?:climbing wall|harness and rope)"],
    "weightlifting": [r"weight ?lift\w*", r"(?:lifts?|lifting) (?:a|weights|the) ?(?:barbell|dumbbell|weights)?", r"(?:barbells?|dumbbells?|kettlebells?)", r"(?:powerlift|bodybuild|crossfit)\w*", r"(?:gym|workout|work(?:s|ing) out)"],
    "rowing": [r"row(?:s|ing|ers?)\b", r"kayak\w*", r"canoe\w*", r"paddl\w+"],
    "skiing": [r"ski\w*", r"snowboard\w*", r"(?:slopes?|chairlift|ski lift)"],
    "boxing": [r"box(?:er|ers|ing)\b", r"(?:martial arts|karate|judo|taekwondo|kickbox\w*|wrestl\w*|fencing|sparring)"],
    # Technology & Electronics
    "desktop computer": [r"(?:desktop )?computers?", r"(?:computer )?monitors?", r"(?:pc|imac)\b", r"(?:keyboard and mouse)"],
    "gaming PC": [r"(?:gaming|custom|glowing|rgb) (?:pc|computer|setup|rig|keyboard)", r"(?:computer|pc) (?:case|tower|build)", r"(?:glowing|backlit|illuminated) keyboard"],
    "computer GPU": [r"(?:graphics card|gpu|motherboard|computer (?:parts|components|hardware|chip)s?)", r"(?:circuit|printed circuit|electronic) boards?", r"(?:microchips?|processors?|chips?\b|cpu)"],
    "smartwatch": [r"smart ?watch\w*", r"(?:fitness tracker|wearable)", r"(?:digital )?watch(?:es)? on (?:his|her|a) wrist"],
    "server rack": [r"servers?\b", r"(?:server|network|equipment) (?:rack|room|cabinet)s?", r"(?:racks? of|rows of) (?:equipment|servers|computers)", r"(?:network|ethernet) (?:switch|cables?)", r"cables\b"],
    "VR headset": [r"(?:vr|virtual reality|augmented reality|ar) (?:headset|goggles|glasses|experience)?", r"headsets?", r"goggles"],
    "wireless earbuds": [r"(?:ear ?buds?|earphones?|headphones?|airpods)"],
    "3D printer device": [r"3d print\w*"],
    "smart speaker": [r"(?:smart |bluetooth |portable )?speakers?\b", r"(?:alexa|echo|google home)"],
    "router": [r"(?:wi-?fi|wireless|network|internet) (?:router|device|equipment|antenna|modem)s?", r"routers?", r"modems?", r"antennas?"],
    "solid state drive": [r"(?:hard|solid state|usb|flash|external) drives?", r"(?:ssd|hdd)\b", r"(?:memory|sd) cards?", r"(?:storage|electronic) devices?", r"(?:electronic|computer) components"],
    "e-reader": [r"(?:e-?readers?|kindle)", r"(?:reads?|reading) (?:on )?(?:a|an) (?:tablet|device)"],
    "tablet computer": [r"(?:tablets?\b|ipads?)", r"(?:touch ?screens?|digital devices?)"],
    # Tools & Equipment
    "screwdriver": [r"screwdrivers?", r"(?:hand ?tools|tool set|tools? (?:on|hanging|laid|arranged))"],
    "power drill": [r"(?:power |electric |cordless )?drills?\b", r"drilling"],
    "saw": [r"(?:hand ?|circular |table |band |miter )?saws?\b", r"sawing", r"sawmill"],
    "wrench": [r"wrench\w*", r"spanners?", r"(?:repair|mechanic'?s?) tools?"],
    "pliers": [r"pliers", r"(?:wire )?cutters", r"(?:clamps?|vise|vice)\b"],
    "measuring tape": [r"(?:measuring|tape) (?:tape|measure)", r"rulers?", r"(?:measures?|measuring) (?:a|the)", r"(?:yardstick|calipers?)"],
    "toolbox": [r"tool ?(?:box|kit|chest|bag|belt|shed|rack)", r"(?:assortment|collection|set|array|variety) of tools", r"tools\b"],
    "welder": [r"weld\w*", r"(?:sparks?|blowtorch|torch|soldering)"],
    "multimeter": [r"multimeters?", r"(?:electrical|electronic) (?:test\w*|meter|equipment|tools?)", r"(?:gauges?|meters?|dials?)\b", r"electricians?"],
    "angle grinder": [r"grind\w*", r"(?:sparks? fly\w*|cutting (?:metal|steel))", r"(?:metal ?work\w*|metalwork\w*)"],
    "nail gun": [r"nail ?guns?", r"(?:roof\w*|framing|carpent\w+)", r"(?:hammer\w* (?:a )?nails?|nails\b)"],
    "socket set": [r"sockets?\b", r"(?:ratchet|bolts?|nuts and bolts|spanner)\w*"],
    "level tool": [r"(?:spirit |bubble |laser )?levels?\b", r"(?:surveyor|surveying|theodolite|tripod)", r"(?:masonry|bricklay\w*|tiling|plaster\w*)"],
    "paint sprayer": [r"(?:spray ?(?:paint\w*|gun|can)s?)", r"(?:paint\w* (?:a|the) (?:wall|house|fence|room|car))", r"painters?\b", r"(?:paint (?:roller|brush|can|bucket)s?)"],
    "hammer": [r"hammers?", r"mallets?", r"sledgehammers?"],
    "chainsaw": [r"chainsaws?", r"(?:cutting|chopping|felling|splitting) (?:down )?(?:a )?(?:tree|trees|wood|logs|firewood)", r"(?:axe|axes|lumberjack|logging|firewood)\b"],
    # Toys & Games
    "wooden building blocks": [r"(?:wooden |building |toy |alphabet )?blocks\b", r"(?:lego|duplo|jenga)\w*", r"(?:building|construction) toys?"],
    "stuffed teddy bear": [r"teddy ?bears?", r"(?:stuffed|plush|soft) (?:animals?|toys?|bears?)", r"plush\w*"],
    "toy train set": [r"(?:toy|model|miniature) (?:trains?|railway|railroad)s?", r"(?:model train|train set)", r"miniature"],
    "board game pieces": [r"(?:game|chess|board game) pieces", r"(?:dice|chessboard|chess pieces|game board|checkers|dominoes|mahjong)"],
    "puzzle pieces": [r"(?:jigsaw )?puzzles?", r"rubik"],
    "action figure": [r"action figures?", r"(?:figurines?|toy soldiers?|superhero (?:toy|figure)s?)", r"(?:collectible|small|plastic) (?:figures?|toys?)"],
    "toy robot": [r"(?:toy|small|tin|miniature|lego) robots?", r"robots?"],
    "dollhouse": [r"doll ?houses?", r"(?:miniature|tiny|model) (?:house|room|furniture|village|town|scene)s?", r"dolls?\b"],
    "kite": [r"kites?\b", r"kitesurf\w*"],
    "yo-yo": [r"yo-?yos?", r"(?:spinning tops?|juggl\w+|hula hoops?|frisbee|diabolo)"],
    "marbles collection": [r"marbles\b", r"(?:glass|colou?rful) (?:balls|beads|spheres)", r"beads\b"],
    "toy car collection": [r"(?:toy|model|miniature|die-?cast|matchbox|hot wheels|scale) (?:cars?|vehicles?|trucks?)", r"(?:model|scale) (?:cars?|kits?|replica)"],
    "video game controller": [r"(?:game |video game |xbox |playstation |gaming )?controllers?", r"joysticks?", r"(?:gamepad|game console|video games?|gaming)"],
    "playing cards": [r"(?:playing )?cards\b", r"(?:poker|blackjack|card game|deck of cards|tarot)"],
    # Transportation & Vehicles
    "subway train": [r"(?:subway|metro|underground|commuter|light rail) (?:trains?|cars?|stations?|platforms?)", r"(?:trams?|streetcars?|trolleys?)\b", r"(?:subway|metro)\b", r"trains?\b"],
    "electric car": [r"(?:electric|hybrid|ev) (?:cars?|vehicles?)", r"(?:tesla|charging station|charging port|charger)", r"(?:sports|modern|luxury|red|white|black|blue|silver) cars?", r"cars?\b"],
    "cargo van": [r"vans?\b", r"(?:delivery|box|pickup|cargo|work) (?:trucks?|vehicles?)", r"trucks?\b", r"lorr(?:y|ies)"],
    # Travel & Tourism
    "beach resort": [r"(?:beach|seaside|luxury|tropical|holiday) (?:resort|hotel|villa|bungalow)s?", r"resorts?", r"(?:beach|lounge|deck) chairs", r"(?:sun ?loungers|umbrellas on the beach|beach umbrellas?)", r"sunbath\w+"],
    "mountain lodge": [r"(?:mountain|ski|alpine|wooden) (?:lodge|chalet|hut|inn|cabin)s?", r"(?:lodges?|chalets?)\b"],
    "city hotel": [r"hotels?\b", r"(?:hotel|inn|motel|hostel) (?:building|facade|entrance|sign)", r"(?:motel|hostel|inn)s?\b"],
    "train journey": [r"(?:train|railway|rail) (?:journey|ride|travel|window|passengers?|tracks?|line|bridge)", r"(?:passengers?|travelers?) (?:on|board\w*) (?:a|the) train", r"railroad tracks?", r"(?:railway|railroad)"],
    "road trip": [r"(?:road ?trip|driving|drives|driver)", r"(?:car|vehicle|jeep|suv) (?:on|driving|parked (?:on|by|along)) (?:a|the) (?:road|highway|dirt road)", r"(?:open|winding|empty|long|desert|country|mountain) roads?", r"highways?"],
    "camping trip": [r"camp(?:ing|site|sites|ground|ers?)\b", r"tents?\b", r"campfire"],
    "hiking trail": [r"hik(?:e|es|er|ers|ing)\b", r"trek\w*", r"(?:trail|footpath|path) (?:through|in|along|winding)", r"backpackers?", r"trails?\b"],
    "historic old town": [r"(?:old|historic|medieval) (?:town|city|village|quarter|center|centre)", r"(?:cobblestone|narrow) (?:streets?|alleys?|lanes?)", r"(?:town|market) square", r"villages?\b"],
    "tropical beach": [r"(?:tropical|sandy|white sand|palm-fringed|secluded) beach(?:es)?", r"palm trees? (?:on|along|line)", r"beach(?:es)?\b"],
    "snow resort": [r"(?:ski|snow|winter) (?:resort|slope|lodge|village|town)s?", r"(?:snow-covered|snowy) (?:village|town|mountain|slope|landscape)", r"(?:chairlifts?|ski lifts?|gondolas?)"],
    "desert travel": [r"desert\w*", r"(?:camels?|dunes?)\b", r"(?:arid|dry|sandy|barren) (?:landscape|terrain|plain|land)", r"(?:canyon|mesa|butte)s?"],
    "safari trip": [r"safari", r"(?:game drive|national park|wildlife reserve|savann?ah?)", r"(?:elephants|lions|giraffes|zebras|wildebeest)"],
    "backpacking adventure": [r"backpack(?:er|ers|ing|s)?\b", r"(?:traveler|traveller|tourist)s? (?:with|carrying|walk\w*)", r"(?:hitchhik\w+|trekk\w+)"],
    "cultural landmark visit": [r"(?:tourists?|visitors?|crowds?) (?:visit\w*|gather\w*|explor\w*|stand\w*|walk\w*|admir\w*|at|in front of|outside)", r"(?:landmark|monument|memorial|statue|temple|cathedral|pyramid|tower)s?\b", r"(?:tourists?|sightseeing)"],
    "island hopping trip": [r"(?:ferr(?:y|ies)|boats? (?:ride|trip|tour)|(?:small |wooden |fishing )?boats?)\b", r"islands?\b", r"(?:long-?tail|speed) ?boats?"],
    "road trip campervan": [r"(?:camper ?vans?|motor ?homes?|rvs?\b|caravans?|camper|trailers?|vw bus|volkswagen (?:bus|van))"],
    "airport terminal": [r"airports?", r"(?:terminal|departure|arrivals?|boarding) (?:hall|gate|lounge|board)", r"(?:runway|tarmac)"],
    "cruise ship": [r"cruise\w*", r"(?:ocean liner|passenger ship)"],
    # Weather & Sky
    "thunderstorm": [r"thunder ?storms?", r"storm\w*", r"(?:dark|ominous|stormy|threatening|heavy) (?:clouds|sky|skies)", r"(?:heavy|pouring|torrential) rain"],
    "snowfall": [r"snow(?:fall|ing|flakes?|y|-covered|storm)?\b", r"(?:falling|fresh) snow"],
    "cloudscape": [r"clouds?\b", r"(?:cloudy|overcast) sky", r"cumulus"],
    "sunrise sky": [r"sunrise", r"dawn", r"(?:early )?morning (?:sky|light|sun|mist)", r"daybreak"],
    "sunset sky": [r"sunsets?", r"dusk", r"twilight"],
    "hail storm": [r"hail\w*", r"(?:ice|sleet|freezing rain)", r"(?:rain ?storm|downpour|rainy|rain\b)"],
    "tornado": [r"tornado\w*", r"(?:funnel|wall) clouds?", r"(?:storm|supercell|shelf cloud)\w*", r"(?:storm|tornado|hurricane) damage", r"(?:destroyed|damaged) (?:house|home|building)s?"],
    "hurricane clouds": [r"hurricanes?", r"(?:storm|dark|heavy|ominous|massive) clouds", r"(?:flood\w*|high winds|storm surge)"],
    "hazy sky": [r"ha(?:ze|zy)", r"(?:smog|mist|misty|smoke|smoky)"],
    "double rainbow": [r"rainbows?"],
    "cirrus clouds": [r"(?:cirrus|wispy|feathery|streaky|thin) clouds", r"(?:blue sky with|clear blue sky)", r"(?:contrails?|vapor trails?)"],
    "golden hour sky": [r"golden (?:hour|light|glow|sunlight)", r"(?:warm|soft|evening|late afternoon) (?:light|sunlight|glow)", r"(?:bathed|glowing) in (?:golden|warm|orange)"],
    "blizzard": [r"blizzards?", r"(?:heavy|blowing|swirling|driving) snow", r"snow ?storms?", r"(?:snow-covered|snowy|frozen|icy|wintry) (?:road|street|landscape|field|forest|trees|scene|mountain)s?"],
    "milky way": [r"milky way", r"(?:night sky|starry sky|stars) (?:over|above)"],
    "aurora": [r"auroras?", r"northern lights", r"aurora borealis"],
    "lightning": [r"lightning", r"(?:bolt|flash|strike)s? of lightning"],
    "starry night": [r"starry", r"(?:night sky|stars)"],
}


from megalith_aliases_extra import EXTRA as _EXTRA  # noqa: E402

for _k, _v in _EXTRA.items():
    ALIASES.setdefault(_k, []).extend(_v)
