"""
Second-pass Megalith caption patterns, added once the common subcategories had
filled: broader, class-level patterns for the subcategories still open (e.g. a
rare animal also accepts its close relatives). Merged into ALIASES by
megalith_aliases.py; exact names and first-pass aliases still win because
they come first in each subcategory's alternation.
"""

EXTRA: dict[str, list[str]] = {
    "paint splash": [r"(?:splashes|drips|streaks|smears|blotches) of (?:paint|colou?r)", r"paint(?:ed)? (?:drips|splotches|strokes)", r"(?:abstract|colou?rful) (?:painting|artwork|pattern)"],
    "paper texture": [r"(?:sheets?|pieces?|scraps?|stacks?) of paper", r"(?:paper|cardboard) (?:cut-?outs?|crafts?|lanterns?)", r"origami", r"torn paper"],
    "fabric texture": [r"(?:folded|draped|colou?rful|patterned) (?:fabric|cloth|textiles?|blankets?|quilts?)", r"(?:rolls|bolts|pile) of (?:fabric|cloth)", r"(?:lace|silk|velvet|wool|linen)\b"],
    "liquid marbling": [r"swirl\w*", r"(?:oil|ink|paint) (?:in|on) water", r"(?:psychedelic|kaleidoscop\w+)"],
    "sand texture": [r"sandy (?:beach|shore|ground|surface|path)", r"(?:grains|patterns) (?:of|in) (?:the )?sand", r"sandcastles?"],
    "water ripples": [r"(?:calm|still|clear|shallow|rippling|shimmering) water", r"water (?:droplets|drops|splash\w*)", r"splash\w*", r"droplets?"],
    "bokeh lights": [r"(?:blurry|blurred|soft-focus|out-of-focus) background", r"(?:string|fairy|christmas|twinkling) lights", r"(?:glowing|sparkling) lights"],
    "marble texture": [r"marble\b", r"granite", r"(?:polished|stone) (?:floor|surface|countertop)"],
    "irrigation system": [r"(?:canals?|ditch(?:es)?|water channels?|water pumps?)\b", r"(?:garden hoses?|watering can|water tower)", r"(?:reservoirs?|water tanks?)"],
    "poultry farm": [r"chickens?\b", r"roosters?", r"(?:ducks|geese|turkeys) (?:on a farm|in a pen|in a yard)", r"eggs? (?:in a|on a) (?:basket|carton|nest)", r"chicks\b"],
    "farmers market stall": [r"(?:market|vendor|stall|stand)s? (?:selling|with|display\w*)", r"(?:crates|baskets|piles|bins) of (?:fruit|vegetables|produce|apples|tomatoes)", r"produce\b", r"greengrocer"],
    "vegetable field rows": [r"(?:farmland|farm fields?|cultivated fields?|agricultural (?:fields?|land))", r"(?:plowed|ploughed|tilled) (?:field|soil|land)", r"(?:crops|seedlings)\b"],
    "dairy farm": [r"cows?\b", r"calves\b", r"calf\b", r"(?:cattle|livestock) (?:barn|shed|farm)"],
    "orchard": [r"(?:apples?|cherries|pears?|peaches|oranges|olives|lemons) (?:on|hanging|growing)", r"fruit trees?", r"(?:blossoming|flowering) trees?"],
    "beekeeping apiary": [r"bees?\b", r"honey\b", r"hives?\b"],
    "vineyard": [r"vines?\b", r"grapes?\b", r"grapevines?"],
    "wheat field": [r"(?:grain|barley|oats|rye|corn|maize|hay) (?:field|crop|stalks)", r"(?:golden|amber) fields?"],
    "koala": [r"(?:marsupial|possum|opossum|wombat)s?\b", r"sloths?"],
    "cheetah": [r"(?:big|wild) cats?", r"(?:lynx|bobcat|cougar|puma|jaguar|serval|ocelot|caracal)s?\b"],
    "kangaroo": [r"(?:marsupial|wombat)s?\b", r"(?:deer|antelope|gazelle|impala|reindeer|caribou)s?\b"],
    "hippopotamus": [r"(?:water buffalo|buffaloes|tapir|manatee)s?\b"],
    "rhinoceros": [r"elephants?\b"],
    "wild boar": [r"(?:raccoon|badger|skunk|porcupine|armadillo|hedgehog)s?\b"],
    "gorilla": [r"(?:primates?|baboons?|lemurs?|macaques?|gibbons?)"],
    "hyena": [r"(?:coyote|dingo|jackal|fox)e?s?\b"],
    "bison": [r"(?:yak|musk ?ox|highland cattle|longhorn)s?\b", r"buffalo\b"],
    "wolf": [r"wol(?:f|ves)\b", r"(?:husky|huskies|coyotes?|wolfdogs?)"],
    "zebra": [r"(?:wild (?:horse|ass)|mustang|donkey)s?\b"],
    "moose": [r"(?:elk|stag|reindeer|caribou|deer)\b"],
    "opera house": [r"(?:opera|concert hall|playhouse)\b", r"(?:grand|ornate|historic) (?:hall|building|facade)"],
    "luxury villa": [r"(?:large|grand|elegant|luxurious|stately|spacious|historic) (?:house|home|residence|estate)s?", r"(?:houses?|homes?) with (?:a )?(?:pool|garden|balcony|terrace)", r"poolside"],
    "modern skyscraper": [r"(?:tall|high-rise|glass|modern) (?:buildings?|towers?)"],
    "mosque": [r"minarets?", r"(?:domes?|domed) (?:building|roof|structure)", r"(?:islamic|moorish|ottoman) (?:architecture|building|arch)"],
    "charcoal drawing": [r"(?:black and white|monochrome|grayscale) (?:drawing|sketch|illustration)", r"(?:ink|pen) (?:drawing|sketch|illustration)", r"illustrations?"],
    "watercolor painting": [r"watercolou?rs?", r"(?:paintings?|artwork|art piece|canvas)\b", r"(?:paint|paints) (?:set|palette|brush)"],
    "manicure": [r"(?:fingernails?|nail salon)\b", r"hands? (?:with|wearing) (?:rings|polish)"],
    "eyeshadow palette": [r"make-?up\b", r"cosmetics?\b", r"beauty (?:products?|salon|kit)"],
    "eyebrow shaping": [r"(?:close-up|closeup) of (?:a|her|his) (?:face|eye|eyes)"],
    "face mask treatment": [r"(?:facial|beauty|skin) (?:treatment|care|mask)", r"(?:spa|salon) (?:treatment|day)"],
    "nail polish set": [r"polish\b", r"varnish\b"],
    "perfume": [r"(?:scent|aroma|essential oils?|incense)\b"],
    "hairbrush": [r"(?:brushing|combing) (?:her|his|their) hair", r"hair ?(?:brush|comb|accessories|clips?|ties)"],
    "lipstick": [r"lips(?:tick)?\b", r"(?:red|pink) lips"],
    "electric razor": [r"(?:grooming|clippers?|trimmer)\b"],
    "barber haircut": [r"(?:hair ?cut|salon|barbershop)\b"],
    "ostrich": [r"(?:cassowar\w+|turkeys?|peahen|guinea ?fowl)\b"],
    "kingfisher": [r"(?:colou?rful|bright|blue|small) birds?", r"birds? (?:perched|perches|sitting) on (?:a|the) (?:branch|wire|twig)"],
    "peacock": [r"peafowl", r"peahens?", r"pheasants?", r"(?:colou?rful|vibrant) (?:feathers|plumage)"],
    "woodpecker": [r"birds? (?:on|clinging to|perched on) (?:a|the) (?:tree|trunk|bark|log|post)"],
    "parrot": [r"(?:colou?rful|green|red|tropical) birds?", r"(?:budgie|cockatiel|lorikeet|lovebird)s?\b"],
    "toucan": [r"(?:tropical|exotic|colou?rful) birds?", r"(?:large|long|big|colou?rful) (?:beak|bill)"],
    "flamingo": [r"flamingoes", r"(?:pink|wading) birds?", r"spoonbills?"],
    "pigeon": [r"doves?\b", r"(?:city|urban|park) birds"],
    "vulture": [r"birds? of prey", r"raptors?", r"(?:eagle|condor)s?\b"],
    "heron": [r"egrets?", r"(?:wading|water) ?birds?", r"shorebirds?", r"storks?", r"ibis\w*"],
    "penguin": [r"(?:puffins?|auks?|gannets?|cormorants?)"],
    "falcon": [r"birds? of prey", r"raptors?", r"eagles?", r"falcon(?:er|ry)"],
    "robin": [r"(?:small|little) birds?", r"birds? (?:perched|perches|sits|sitting) on (?:a|the) (?:branch|fence|twig)", r"birds?\b"],
    "owl": [r"owlets?"],
    "real estate agent": [r"(?:houses?|homes?|apartments?) (?:for sale|for rent|under construction)", r"(?:realtor|property|properties)\b"],
    "mechanic at work": [r"(?:car|auto|motorcycle|bike|bicycle|engine|tire|tyre) (?:repair|shop|garage|maintenance)", r"(?:works?|working) on (?:a|an|the) (?:car|engine|vehicle|truck|aircraft|plane|motorcycle|bicycle|bike)", r"maintenance\b", r"technicians?"],
    "farmer at work": [r"(?:rural|farm|field) (?:workers?|labou?rers?)", r"(?:herding|feeding|milking|tending) (?:cattle|cows|sheep|goats|animals|livestock|crops)", r"(?:working|works) (?:the|in the|on the) (?:land|farm|soil)", r"(?:shepherd|herder)s?\b"],
    "software developer": [r"(?:typing on|looking at) (?:a|his|her) (?:computer|laptop|keyboard|screen|monitor)"],
    "artisan market": [r"(?:bazaar|souk|stalls|vendors)\b", r"(?:handmade|handcrafted) (?:goods|items|jewelry|crafts)", r"souvenirs?"],
    "regional cuisine": [r"(?:plate|bowl|platter) of (?:traditional|local|homemade)", r"(?:feast|spread of food|home-?cooked meal)"],
    "folk instrument making": [r"(?:craftsm[ae]n|artisans?|woodworkers?)\b", r"(?:hand-?made|handcrafted|hand-?carved)"],
    "folk dance": [r"(?:dancers?|dance troupe|dance performance)\b", r"(?:traditional|folk|cultural) (?:costumes?|dress|attire|performance)"],
    "harvest celebration": [r"(?:harvest|autumn|fall|pumpkin|apple|corn) (?:festival|fair|market|display|patch|picking)", r"(?:gourds?|scarecrows?)\b"],
    "calligraphy": [r"(?:handwriting|inscriptions?|chinese characters|arabic script|written in ink)"],
    "weaving": [r"(?:baskets?|woven|rugs?|carpets?)\b"],
    "protein shake": [r"(?:fitness|workout|gym) (?:drink|supplement|nutrition)", r"(?:glass|bottle|jug) of milk", r"(?:yogurt|yoghurt)\b"],
    "hot chocolate": [r"(?:steaming|hot|warm) (?:drink|beverage|mug|cup)", r"marshmallows?", r"(?:mug|mugs) of"],
    "smoothie": [r"(?:blender|juicer)\b", r"(?:fruit|berry|green) (?:drink|juice|shake)"],
    "herbal infusion": [r"tea\b", r"(?:teapot|infuser)\b", r"(?:fresh )?(?:mint|chamomile|hibiscus|lemongrass) (?:leaves|flowers)"],
    "lemonade": [r"(?:limes?|citrus)\b", r"(?:pitcher|jug) of", r"(?:cold|refreshing|iced) (?:drink|beverage)"],
    "coconut water": [r"palm (?:fruits?|nuts?)", r"(?:tropical|fresh) (?:fruit|drink)"],
    "fruit juice": [r"(?:pineapples?|mangoes|mangos?|grapefruits?|pomegranates?|watermelons?)\b", r"(?:fresh|sliced|cut) fruits?"],
    "iced coffee": [r"coffee\b"],
    "sparkling water": [r"(?:bubbles|bubbly|fizz\w*|carbonated)\b", r"water (?:glass|bottle)s?"],
    "soda": [r"(?:vending machines?|soft drinks?)\b"],
    "retirement party": [r"(?:party|luncheon)\b", r"(?:balloons|streamers|banners?)\b"],
    "trade show": [r"(?:expo|convention|booths?|exhibitors?)\b", r"displays? of (?:products|cars|equipment)"],
    "wedding reception": [r"weddings?\b", r"(?:bride|groom|newlyweds?|bridal)\b", r"(?:reception|banquet) (?:hall|table|venue)"],
    "space station": [r"(?:orbital|lunar|mars) (?:station|habitat|module|base|colony)", r"(?:spacecraft|space shuttle|capsule)s?\b", r"mission control"],
    "fantasy castle": [r"(?:palace|chateau|château|citadel|fortress|kremlin)s?\b", r"(?:towers and turrets|spires?)\b"],
    "cyberpunk city": [r"(?:city|street|streets|skyline) (?:at night|lit up|illuminated)", r"(?:neon|glowing) (?:lights|signs|billboards)", r"(?:times square|shinjuku|shibuya|las vegas)"],
    "floating islands": [r"(?:islands?|islets?|atolls?|rocks?) (?:in|rising from|jutting out of) (?:the|a) (?:sea|ocean|lake|water|mist|clouds)", r"(?:mountains?|peaks?|summits?) (?:above|in|shrouded in) (?:the )?(?:clouds|mist|fog)"],
    "elf warrior": [r"(?:costumed|cosplay\w*|dressed as)\b", r"(?:warriors?|archers?|swords?|bow and arrow|shields?|spears?)\b"],
    "knight": [r"(?:jousting|chain ?mail|medieval (?:festival|fair|reenactment))"],
    "alien planet": [r"(?:barren|volcanic|desolate|surreal|strange) (?:landscape|terrain|rocks?|formations?)", r"(?:geysers?|hot springs?)\b"],
    "mech suit": [r"(?:robotic|mechanical) (?:suit|arm|figure|costume)", r"exoskeletons?"],
    "business suit": [r"(?:suit and tie|blazer|jacket and tie|formal attire|tuxedo)\b", r"(?:executives?|officials?|politicians?|diplomats?|dignitaries|mayor|senator|ambassador)s?\b"],
    "casual outfit": [r"(?:t-shirt|jeans|shorts|hoodie|sweater|tank top|flannel)\b"],
    "jewelry": [r"(?:necklace|bracelet|earring|pendant|brooch|gemstone|diamond|pearl)s?\b"],
    "denim jacket": [r"(?:jean|leather|bomber|puffer|rain) (?:jacket|coat|vest)s?", r"jackets?\b", r"denim\b"],
    "vegan bowl": [r"(?:tofu|quinoa|avocado|lentils|chickpeas)\b", r"bowls? of (?:greens|beans|grains)"],
    "curry": [r"(?:indian|thai|sri lankan|pakistani) (?:dish|food|meal|cuisine)", r"(?:dal|naan|biryani|masala)\b"],
    "pasta": [r"(?:italian (?:dish|food|meal|cuisine|restaurant)|pizzas?)\b"],
    "rice dish": [r"(?:asian|chinese|japanese|korean|thai|vietnamese) (?:dish|food|meal|cuisine)"],
    "tacos": [r"(?:mexican|latin) (?:food|dish|restaurant|cuisine)", r"(?:salsa|guacamole|quesadillas?|enchiladas?)"],
    "soup": [r"soups?\b", r"(?:broth|chowder)\b"],
    "dumplings": [r"(?:steamed|fried|boiled) (?:buns?|dough|pastries)", r"(?:bao|gyoza|momo|wontons?|spring rolls?)\b"],
    "dessert": [r"(?:sweets|ice cream|chocolates|candy|candies|pudding)\b"],
    "sushi": [r"(?:japanese (?:food|dish|restaurant|cuisine)|bento|onigiri|raw fish)\b"],
    "salad": [r"(?:lettuce|leafy greens)\b"],
    "steak": [r"(?:meat|pork|lamb)\b"],
    "burger": [r"(?:fast food|french fries)\b"],
    "ramen": [r"noodles?\b"],
    "sandwich": [r"(?:subs|wraps?|bagels?|baguettes?)\b"],
    "seafood platter": [r"(?:scallops?|salmon|tuna|squid)\b"],
    "cheese board": [r"(?:platter|board|spread|tray) of", r"(?:wine and cheese|olives)\b"],
    "old camera": [r"cameras?\b", r"(?:camera|photography) (?:equipment|gear|collection|shop|museum)"],
    "typewriter": [r"(?:office|desk) (?:equipment|supplies)"],
    "retro diner": [r"(?:diner|cafe|café|eatery|bistro|cafeteria)s?\b", r"(?:counter stools|booths?)\b"],
    "vinyl record player": [r"(?:stereo|hi-?fi|audio|sound) (?:system|equipment)", r"(?:amplifiers?|albums?)\b"],
    "vintage radio": [r"(?:vintage|old|antique|retro|old-fashioned) (?:device|machine|equipment|electronics|appliance|telephone|phone)", r"(?:rotary phone|phone booth)"],
    "old factory": [r"(?:factory|factories|mills?|industrial)\b", r"(?:brick|stone) (?:chimney|warehouse)"],
    "coffee maker": [r"coffee\b", r"(?:kitchen|countertop) appliances?", r"(?:toaster|microwave|blender|mixer)s?\b"],
    "vacuum cleaner": [r"(?:cleaners?|janitor|housekeeping|dusting)\b", r"(?:household|home) (?:chores|appliances?)"],
    "curtains": [r"(?:curtains?|drapes?|blinds)\b", r"windows? with"],
    "refrigerator": [r"(?:fridge|freezer|cooler|appliances)\b"],
    "washing machine": [r"(?:laundromat|clothesline|laundry)\b"],
    "bookshelf": [r"(?:shelf|shelves|shelving|bookcase)\b"],
    "kitchen utensils": [r"(?:cookware|knife|knives|spoons?|forks?)\b"],
    "working from home": [r"laptops?\b", r"(?:kitchen table|couch|sofa)\b"],
    "washing a car": [r"(?:cars?|vehicles?|trucks?) (?:being|getting) (?:washed|cleaned)", r"(?:hose|suds|sponge|bucket)\b"],
    "cooking": [r"(?:cook|cooks|stove|frying|grilling)\b"],
    "data center": [r"(?:computer|electronic|technology|network|control) (?:room|equipment|center|centre|lab|facility|system)", r"(?:servers?|racks?|wiring)\b"],
    "laboratory equipment": [r"(?:scientific|research) (?:equipment|instruments?|facility|setting)", r"(?:lab|laboratory)\b"],
    "3D printing factory floor": [r"(?:prototypes?|manufacturing|fabrication|makerspace)\b"],
    "steel mill": [r"(?:molten|furnaces?|smelting|forging|foundry|sparks)\b", r"(?:steel|iron) (?:works|plant|beams?|structure)"],
    "oil refinery": [r"industrial (?:plant|site|complex|facility)", r"(?:storage tanks|smokestacks?|gas flare)\b"],
    "industrial robot arm": [r"(?:robotic|automation|automated|machinery)\b"],
    "solar farm": [r"(?:solar|photovoltaic|renewable energy)\b"],
    "shipping container yard": [r"(?:containers?|freight|cargo|docks?)\b"],
    "praying mantis": [r"(?:insects?|bugs?|katydids?)\b"],
    "centipede": [r"(?:crawl\w*|larvae|grubs?)\b"],
    "snail": [r"(?:shells?|mollusks?|molluscs?)\b"],
    "firefly": [r"(?:beetles?|moths?)\b"],
    "dragonfly": [r"(?:damselfl(?:y|ies)|mayfl(?:y|ies)|winged insects?)"],
    "caterpillar": [r"(?:larvae|larva|cocoons?|chrysalis|butterfl(?:y|ies))\b"],
    "hotel room": [r"(?:bedroom|suite|guest room|motel)\b"],
    "dining room": [r"(?:dining|dinner table|tables? (?:set|laid))\b"],
    "walk-in closet": [r"(?:hangers|clothing racks?|shoe racks?)\b"],
    "weather map": [r"(?:meteorolog\w+|forecast|radar|wind (?:vane|sock))\b"],
    "world map": [r"(?:atlas|globes?|charts?)\b"],
    "treasure map style": [r"(?:old|antique|ancient|historic|historical) (?:documents?|papers?|manuscripts?|letters?|charts?)", r"(?:gold coins|jewels)\b"],
    "subway transit map": [r"(?:subway|metro|transit)\b"],
    "globe": [r"(?:spheres?|orbs?)\b"],
    "walrus": [r"(?:seals?|marine mammals?|pinnipeds?)\b"],
    "orca": [r"(?:whales?|marine mammals?|porpoises?)\b"],
    "eel": [r"(?:snakes?|sea snakes?)\b"],
    "sea turtle": [r"turtles?\b", r"(?:snorkel\w*|scuba)\b"],
    "seahorse": [r"(?:aquariums?|fish tanks?|marine life)\b"],
    "manta ray": [r"(?:rays?|stingrays?)\b"],
    "dolphin": [r"(?:porpoises?|marine mammals?)\b"],
    "clownfish": [r"(?:fish|fishes)\b"],
    "jellyfish": [r"(?:translucent|glowing) (?:sea|marine|underwater)", r"aquarium"],
    "crab": [r"(?:crustaceans?|shellfish|crayfish)\b"],
    "blue whale": [r"(?:whales?|whale watching)\b"],
    "sea otter": [r"(?:otters?|beavers?)\b"],
    "hammerhead shark": [r"(?:sharks?|underwater)\b"],
    "octopus": [r"(?:tentacles?|squid|cephalopods?|marine|underwater)\b"],
    "lobster": [r"(?:crustaceans?|shellfish|seafood)\b"],
    "arcade": [r"(?:claw machines?|amusement|carnival|fairground|midway|video games?)\b"],
    "movie set": [r"(?:filming|film crew|camera crew|studio|actors?|actresses?|production)\b"],
    "video game setup": [r"(?:console|consoles|television|tv)\b"],
    "street performer": [r"(?:performers?|entertainers?|magicians?|puppets?|puppeteers?)\b"],
    "X-ray equipment": [r"(?:medical|hospital|diagnostic|clinical|imaging|scanning|radiology) (?:equipment|machine|device|room|scan|images?|screen)", r"(?:skeleton|bones|skull)\b"],
    "stethoscope": [r"(?:doctors?|nurses?|physicians?|medical (?:staff|professionals?|workers?|personnel)|health ?care workers?)\b"],
    "pharmacy": [r"(?:medicines?|medications?|pills|prescriptions?|chemist)\b"],
    "field medic training": [r"(?:first aid|triage|rescue|wounded|injured|casualty|casualties|stretchers?)\b"],
    "ambulance": [r"(?:emergency (?:vehicle|services|responders?|medical)|emts?|ems)\b"],
    "dentist office": [r"(?:teeth|tooth|dental)\b"],
    "doctor consultation": [r"(?:clinic|medical (?:office|appointment|visit))\b"],
    "ukulele": [r"(?:guitars?|guitarists?|string instruments?)\b"],
    "harp": [r"(?:stringed instruments?|string instruments?)\b"],
    "accordion": [r"(?:concertinas?|harmonicas?|bagpipes?)\b"],
    "grand piano": [r"(?:pianos?|pianists?)\b"],
    "flute": [r"(?:flutes?|clarinets?|oboes?|recorders?|woodwinds?|piccolos?)\b"],
    "fjord": [r"(?:inlet|cove|estuary)\b"],
    "adult grandparent portrait": [r"(?:elderly|older|senior|aged|old) (?:man|woman|men|women|people|person|couple)"],
    "budgerigar": [r"(?:cage|birdcage|aviary)\b"],
    "ferret": [r"(?:minks?|stoats?|small animals?|rodents?)\b"],
    "guinea pig": [r"(?:rodents?|small (?:animals?|pets?))\b"],
    "hamster": [r"(?:rodents?|small (?:animals?|pets?))\b"],
    "goldfish": [r"(?:fish|pond|koi)\b"],
    "pig": [r"(?:farm animals?|livestock)\b"],
    "puppy": [r"dogs?\b"],
    "rabbit": [r"hares?\b"],
    "golden retriever": [r"(?:dogs?|labradors?|retrievers?)\b"],
    "vegetable garden": [r"(?:gardens?|gardening|garden plots?|allotments?|greenhouses?)\b"],
    "succulent": [r"(?:cact(?:us|i|uses)|aloe|agaves?|potted plants?|houseplants?)\b"],
    "sunflower": [r"(?:yellow flowers?|daisies|daisy)\b"],
    "fern": [r"(?:fronds?|undergrowth|greenery)\b"],
    "autumn leaves": [r"(?:autumn|fall|foliage)\b"],
    "salamander": [r"(?:amphibians?|newts?)\b"],
    "iguana": [r"(?:lizards?|reptiles?)\b"],
    "toad": [r"(?:frogs?|amphibians?)\b"],
    "chameleon": [r"(?:lizards?|reptiles?)\b"],
    "crocodile": [r"(?:reptiles?|caimans?)\b"],
    "alligator": [r"(?:reptiles?|caimans?)\b"],
    "komodo dragon": [r"(?:lizards?|reptiles?)\b"],
    "tree frog": [r"(?:frogs?|amphibians?)\b"],
    "tortoise": [r"(?:turtles?|reptiles?)\b"],
    "bearded dragon lizard": [r"(?:lizards?|reptiles?)\b"],
    "turtle": [r"(?:terrapins?)\b"],
    "gecko": [r"(?:lizards?|reptiles?)\b"],
    "astronomy observatory": [r"(?:telescopes?|domes?|observatory|observatories|satellite dishes?)\b"],
    "chemistry lab": [r"(?:lab|labs|laboratory|laboratories|experiments?|chemicals?)\b"],
    "coding classroom": [r"(?:computers?|laptops?) (?:in a|lab|class)", r"(?:students?) (?:at|using|on) (?:computers?|laptops?)"],
    "genetics lab": [r"(?:lab|labs|laboratory|laboratories|test tubes?)\b"],
    "microscope": [r"(?:magnif\w+|lab|laboratory)\b"],
    "telescope": [r"(?:binoculars|spotting scope|observatory|stargazing)\b"],
    "physics experiment": [r"(?:experiments?|lab|laboratory)\b"],
    "galaxy": [r"(?:stars|starry|night sky|cosmos|universe)\b"],
    "solar eclipse": [r"(?:sun|moon) (?:behind|through|partially|shrouded)"],
    "space station exterior": [r"(?:orbit|orbital|spacecraft|earth from)\b"],
    "nebula": [r"(?:cosmos|universe|galaxy|galaxies|deep space)\b"],
    "mars rover": [r"(?:rovers?|robots?|nasa|spacecraft|landers?|probes?)\b"],
    "meteor shower": [r"(?:night sky|shooting star|long exposure|star trails)\b"],
    "astronaut": [r"(?:cosmonauts?|space ?suits?|nasa|space (?:mission|program|flight|walk))\b"],
    "space telescope": [r"(?:satellites?|spacecraft|probes?)\b"],
    "rocket launch": [r"(?:rockets?|launch pad|lift ?off|missiles?)\b"],
    "e-reader": [r"(?:tablets?|gadgets?|reading device)\b"],
    "gaming PC": [r"(?:computers?|pcs?|keyboards?|monitors?)\b"],
    "3D printer device": [r"(?:printers?|printing)\b"],
    "smartwatch": [r"(?:wristbands?|gadgets?|wearables?)\b", r"watch on (?:his|her) wrist"],
    "router": [r"(?:electronic (?:devices?|equipment)|antennas?)\b"],
    "circuit board": [r"(?:circuits?|electronics?|electronic components?|chips?|soldering)\b"],
    "drone": [r"(?:quadcopters?|uavs?|unmanned (?:aerial|aircraft))\b"],
    "wireless earbuds": [r"(?:headphones?|earphones?|headsets?)\b"],
    "computer GPU": [r"(?:computer hardware|computer components?|chips?)\b"],
    "wrench": [r"(?:bolts?|plumb\w*)\b", r"(?:repairing|fixing) (?:a|the)"],
    "paint sprayer": [r"(?:spray|sprays|spraying)\b", r"painting (?:a|the) (?:wall|house|fence|room|car|boat)"],
    "power drill": [r"(?:drill\w*|construction workers?)\b"],
    "screwdriver": [r"(?:screws?|workbench)\b", r"(?:repairing|fixing) (?:a|an|the)"],
    "saw": [r"(?:lumber|logs?|timber|cutting wood)\b"],
    "socket set": [r"(?:toolbox|garage)\b"],
    "pliers": [r"(?:wires?|wiring|electricians?)\b"],
    "angle grinder": [r"(?:sparks?|cutting metal|cutting steel)\b"],
    "measuring tape": [r"(?:builders?|construction)\b"],
    "hammer": [r"(?:nails?|builders?)\b"],
    "3D printer": [r"(?:printers?|printing|prototypes?)\b"],
    "puzzle pieces": [r"(?:puzzles?|pieces)\b"],
    "video game controller": [r"(?:gamers?|consoles?|joysticks?)\b"],
    "marbles collection": [r"(?:glass (?:balls|beads|spheres))\b"],
    "board game pieces": [r"(?:chess|dice)\b"],
    "hot air balloon": [r"(?:balloons?|blimps?|airships?|zeppelins?)\b"],
    "milky way": [r"(?:night sky|starry|star-filled|astrophotography)\b"],
    "aurora": [r"(?:southern lights|green (?:lights|glow) in the sky)\b"],
    "fog": [r"(?:foggy|mist|misty|haze|hazy)\b", r"clouds? (?:over|covering) (?:the )?(?:hills|mountains|valley|trees|forest)"],
    "lightning": [r"(?:thunder|storm clouds|stormy sky)\b"],
    "tornado": [r"(?:twister|funnel|storm damage|debris|destroyed (?:house|home|building)s?)\b"],
    "double rainbow": [r"(?:prism|spectrum)\b"],
}
